export const TRAVEL_RULES = Object.freeze({
  travelAnchors: Object.freeze([
    "travel",
    "trip",
    "journey",
    "destination",
    "origin",
    "airport",
    "passport",
    "visa",
    "border crossing",
    "immigration",
    "emigration",
    "refugee",
    "exile",
    "deportation",
    "tourism",
    "foreign country",
    "foreign city",
    "country comparison",
    "country insult",
    "country praise",
    "country mockery",
    "country stereotype",
    "country security reference",
    "country political reference",
    "travel_reference",
    "travel_destination",
    "travel_origin",
    "travel_abroad",
    "international_travel",
    "domestic_travel",
    "border_crossing",
    "foreign_country",
    "foreign_city",
    "foreign_government_reference",
    "foreign_people",
    "foreign_culture",
    "foreign_religion",
    "foreign_customs",
    "foreign_landmarks",
    "foreign_language",
    "foreign_food",
    "foreign_event",
    "foreign_media",
    "foreign_law",
    "foreign_police",
    "foreign_military",
    "medical_travel",
    "religious_travel",
    "historical_travel",
    "fictional_travel",
    "dream_travel",
    "flashback_travel",
    "imaginary_country",
    "travel_scene_description",
    "travel_dialogue",
    "travel_observation",
    "country_comparison",
    "country_insult",
    "country_praise",
    "country_mockery",
    "country_stereotype",
    "country_security_reference",
    "country_political_reference",
    "سفر",
    "سافر",
    "يسافر",
    "رحلة",
    "مطار",
    "جواز",
    "فيزا",
    "حدود",
    "هجرة",
    "منفى",
    "ترحيل",
    "بلد",
    "دولة",
    "أجنبي",
    "مقارنة بين الدول",
  ]),
  directTerms: Object.freeze([
    "travel_reference",
    "travel_destination",
    "travel_origin",
    "travel_abroad",
    "international_travel",
    "domestic_travel",
    "border_crossing",
    "airport",
    "passport",
    "visa",
    "foreign_country",
    "foreign_city",
    "foreign_government_reference",
    "foreign_people",
    "foreign_culture",
    "foreign_religion",
    "foreign_customs",
    "foreign_landmarks",
    "foreign_language",
    "foreign_food",
    "foreign_event",
    "foreign_media",
    "foreign_law",
    "foreign_police",
    "foreign_military",
    "tourism",
    "immigration",
    "emigration",
    "refugee",
    "exile",
    "deportation",
    "international_business",
    "international_study",
    "medical_travel",
    "religious_travel",
    "historical_travel",
    "fictional_travel",
    "dream_travel",
    "flashback_travel",
    "imaginary_country",
    "travel_scene_description",
    "travel_dialogue",
    "travel_observation",
    "country_comparison",
    "country_insult",
    "country_praise",
    "country_mockery",
    "country_stereotype",
    "country_security_reference",
    "country_political_reference",
  ]),
  travelTerms: Object.freeze([
    "travel_reference",
    "travel_destination",
    "travel_origin",
    "travel_abroad",
    "international_travel",
    "domestic_travel",
    "border_crossing",
    "airport",
    "passport",
    "visa",
    "tourism",
    "immigration",
    "emigration",
    "refugee",
    "exile",
    "deportation",
    "medical_travel",
    "religious_travel",
    "historical_travel",
    "fictional_travel",
    "dream_travel",
    "flashback_travel",
    "travel_scene_description",
    "travel_dialogue",
    "travel_observation",
    "سفر",
    "سافر",
  ]),
  migrationTerms: Object.freeze([
    "immigration",
    "emigration",
    "refugee",
    "exile",
    "deportation",
    "border crossing",
    "passport",
    "visa",
    "مهاجر",
    "هجرة",
    "منفى",
    "ترحيل",
    "سافر",
  ]),
  countryEvaluationTerms: Object.freeze([
    "country_comparison",
    "country_insult",
    "country_praise",
    "country_mockery",
    "country_stereotype",
    "country_security_reference",
    "country_political_reference",
    "foreign_government_reference",
    "foreign_people",
    "foreign_culture",
    "foreign_religion",
    "foreign_customs",
    "foreign_landmarks",
    "foreign_language",
    "foreign_food",
    "foreign_event",
    "foreign_media",
    "foreign_law",
    "foreign_police",
    "foreign_military",
    "لا تستحق الاحترام",
    "لا يستحق الاحترام",
    "تستحق الاحترام",
  ]),
  quotationSignals: Object.freeze(["quoted", "quote", "quotation", "«", "»", "\"", "اقتباس"]),
  educationalSignals: Object.freeze(["educational", "education", "instruction", "lesson", "شرح", "تعليمي", "درس"]),
  documentarySignals: Object.freeze(["documentary", "وثائقي", "تسجيلي", "archive"]),
  historicalSignals: Object.freeze(["historical", "history", "تاريخي", "تاريخ"]),
  newsSignals: Object.freeze(["news", "خبر", "reported", "report"]),
  courtSignals: Object.freeze(["court", "trial", "testimony", "محكمة", "شهادة"]),
  fictionSignals: Object.freeze(["fiction", "story", "film", "movie", "novel", "رواية", "فيلم", "مسلسل"]),
  satireSignals: Object.freeze(["satire", "satirical", "ساخر", "سخرية", "تهكم"]),
  comedySignals: Object.freeze(["comedy", "comic", "كوميديا"]),
  dreamSignals: Object.freeze(["dream", "حلم", "منام"]),
  flashbackSignals: Object.freeze(["flashback", "استرجاع", "فلاش باك"]),
  rolePlaySignals: Object.freeze(["roleplay", "role play", "acting", "تمثيل", "مسرحية"]),
});
