/**
 * Regression test for the V3 finding mapper.
 * Run: node --import tsx apps/worker/src/analysisEngineV3/runtime/findingMapper.test.ts
 */
import { strict as assert } from "node:assert";

import { createLegalDecision, createLegalFinding } from "../legal/legalResult.js";
import { mapLegalDecisionToFindings } from "./findingMapper.js";

function testLegalArticleWinsOverGcamMapping(): void {
  const legalDecision = createLegalDecision({
    moduleId: "v3_01_religion",
    moduleTitle: "Religion Reviewer",
    articleIds: [8],
    applies: true,
    status: "accept",
    reason: "The quote directly attacks religion.",
    confidence: 0.94,
    semantic: {
      semanticMeaning: "Direct religious insult.",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "speaker",
      listener: "listener",
      target: "target",
      victim: "victim",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.95,
      notes: [],
    },
    narrative: {
      speaker: "speaker",
      listener: "listener",
      target: "target",
      narrativeVoice: "dialogue",
      sceneType: "dialogue",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: "unknown",
      emotionalTone: "hostile",
      condemnation: false,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.95,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "هذا الكلام إساءة دينية",
          startOffset: 10,
          endOffset: 20,
          confidence: 0.94,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.94,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "هذا الكلام إساءة دينية",
      chunkContext: "chunk",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.94,
      notes: [],
    },
    exceptions: [],
    finding: createLegalFinding({
      findingKey: "v3_01_religion:10-20:8:هذا الكلام إساءة دينية:accept",
      moduleId: "v3_01_religion",
      moduleTitle: "Religion Reviewer",
      articleIds: [8],
      status: "accept",
      reason: "The quote directly attacks religion.",
      confidence: 0.94,
      semantic: {
        semanticMeaning: "Direct religious insult.",
        narrativeIntent: "attack",
        conversationRole: "speaker",
        sceneRole: "dialogue",
        speaker: "speaker",
        listener: "listener",
        target: "target",
        victim: "victim",
        emotion: "hostile",
        riskContext: "high",
        confidence: 0.95,
        notes: [],
      },
      narrative: {
        speaker: "speaker",
        listener: "listener",
        target: "target",
        narrativeVoice: "dialogue",
        sceneType: "dialogue",
        narrativeIntent: "attack",
        storyPosition: "middle",
        relationship: "unknown",
        emotionalTone: "hostile",
        condemnation: false,
        approval: false,
        neutrality: false,
        historicalContext: false,
        dream: false,
        flashback: false,
        comedy: false,
        satire: false,
        threat: false,
        instruction: false,
        news: false,
        documentary: false,
        dialogue: true,
        narration: false,
        sceneDescription: false,
        confidence: 0.95,
        notes: [],
      },
      evidence: {
        text: "هذا الكلام إساءة دينية",
        startOffset: 10,
        endOffset: 20,
        confidence: 0.94,
        source: "chunk",
        notes: [],
      },
      context: {
        storyMemory: null,
        sceneMemory: null,
        localContext: "هذا الكلام إساءة دينية",
        chunkContext: "chunk",
        neighboringSentences: [],
        narrativeContext: "dialogue",
        confidence: 0.94,
        notes: [],
      },
      exceptionCodes: [],
    }),
    trace: ["finding_built"],
  });

  const findings = mapLegalDecisionToFindings({
    decision: legalDecision,
    chunkStart: 0,
    chunkEnd: 20,
    startLine: 1,
    endLine: 1,
    diagnostics: {
      engineVersion: "v3",
      providerName: "openai",
      modelName: "gpt-4.1",
      modelVersion: "test",
      rawResponseHash: "raw",
      responseId: "response-1",
      responseTimestamp: "2026-07-16T00:00:00.000Z",
      promptHash: "prompt",
      semanticHash: "semantic",
      legalHash: "legal",
      executionSignatureHash: "execution",
      stageHashes: [],
      stageTimings: [],
      subjectModuleId: "v3_01_religion",
      chunkHash: "chunk",
      findingCount: 1,
    } as never,
    gcamMapping: {
      status: "UNMAPPED",
      articleId: null,
      articleNumber: null,
      articleTitleAr: null,
      atomId: null,
      atomNumber: null,
      atomTitleAr: null,
      findingTitle: "UNMAPPED",
      findingCategory: "UNMAPPED",
      reviewerExplanation: "No official GCAM mapping exists. A mapping debt record was created instead of guessing.",
      supportingEvidence: ["هذا الكلام إساءة دينية"],
      matchedRuleId: null,
      matchedArticleMappingId: null,
      matchedAtomMappingId: null,
      confidence: 0.9,
      mappingDebt: [],
      hash: "hash",
    } as never,
  });

  assert.equal(findings.length, 1);
  assert.equal(findings[0].article_id, 8);
  assert.equal(findings[0].title_ar, "الكراهية والتمييز");
  assert.equal(findings[0].description_ar, "التحريض ضد فئة اجتماعية أو ثقافية أو دينية");
  const locationV3 = (findings[0].location as unknown as { v3?: Record<string, unknown> } | null)?.v3;
  const knowledgeRegistry = locationV3?.knowledge_registry as Record<string, unknown> | null | undefined;
  assert.equal(knowledgeRegistry?.article_reference, 8);
  assert.equal(String(knowledgeRegistry?.source_path ?? "").includes("article_08"), true);
  console.log("✓ legal article 8 resolves through the official GCAM catalog");
}

function testArticleFourteenResolvesFromPolicyCatalog(): void {
  const legalDecision = createLegalDecision({
    moduleId: "v3_03_security",
    moduleTitle: "National Security Reviewer",
    articleIds: [14],
    applies: true,
    status: "accept",
    reason: "The quote directly urges overthrow.",
    confidence: 0.95,
    semantic: {
      semanticMeaning: "Direct overthrow incitement.",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "speaker",
      listener: "listener",
      target: "target",
      victim: "victim",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.95,
      notes: [],
    },
    narrative: {
      speaker: "speaker",
      listener: "listener",
      target: "target",
      narrativeVoice: "dialogue",
      sceneType: "dialogue",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: "unknown",
      emotionalTone: "hostile",
      condemnation: false,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.95,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "سنسقط النظام الليلة",
          startOffset: 12,
          endOffset: 30,
          confidence: 0.96,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.96,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "سنسقط النظام الليلة",
      chunkContext: "chunk-14",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.95,
      notes: [],
    },
    exceptions: [],
    finding: null,
    trace: ["finding_built"],
  });

  const findings = mapLegalDecisionToFindings({
    decision: legalDecision,
    reasonedDecision: {
      reasoning: "The text explicitly urges overthrow.",
      alternativeInterpretations: [],
      confidence: 0.95,
      articleEvaluations: [
        {
          articleId: 14,
          status: "PASS",
          evidence: ["سنسقط النظام الليلة"],
          reason: "The quote directly urges overthrow.",
          confidence: 0.95,
        },
      ],
      supportingEvidence: ["سنسقط النظام الليلة"],
      contradictingEvidence: [],
      applicableArticles: [14],
      rejectedArticles: [],
      riskAnalysis: "Low ambiguity.",
      narrativeAnalysis: "Direct incitement.",
      humanLikeExplanation: "The finding should resolve to the official GCAM article title and atom title.",
      recommendation: "RETURN VIOLATION",
    },
    chunkStart: 0,
    chunkEnd: 30,
    startLine: 1,
    endLine: 1,
    diagnostics: {
      engineVersion: "v3",
      providerName: "openai",
      modelName: "gpt-4.1",
      modelVersion: "test",
      rawResponseHash: "raw",
      responseId: "response-3",
      responseTimestamp: "2026-07-16T00:00:00.000Z",
      promptHash: "prompt",
      semanticHash: "semantic",
      legalHash: "legal",
      executionSignatureHash: "execution",
      stageHashes: [],
      stageTimings: [],
      subjectModuleId: "v3_03_security",
      chunkHash: "chunk",
      findingCount: 1,
    } as never,
    gcamMapping: {
      status: "UNMAPPED",
      articleId: null,
      articleNumber: null,
      articleTitleAr: null,
      atomId: null,
      atomNumber: null,
      atomTitleAr: null,
      findingTitle: "UNMAPPED",
      findingCategory: "UNMAPPED",
      reviewerExplanation: "No official GCAM mapping exists. A mapping debt record was created instead of guessing.",
      supportingEvidence: ["سنسقط النظام الليلة"],
      matchedRuleId: null,
      matchedArticleMappingId: null,
      matchedAtomMappingId: null,
      confidence: 0.95,
      mappingDebt: [],
      hash: "hash",
    } as never,
  });

  assert.equal(findings.length, 1);
  assert.equal(findings[0].article_id, 14);
  assert.equal(findings[0].title_ar, "التحريض على قلب نظام الحكم أو الدعوة إلى العنف");
  assert.equal(findings[0].description_ar, "التحريض الصريح على قلب نظام الحكم");
  console.log("✓ article 14 resolves through the official GCAM catalog");
}

function testPolicyAppliedFindingIsPreserved(): void {
  const legalDecision = createLegalDecision({
    moduleId: "v4_11_profanity",
    moduleTitle: "الألفاظ النابية",
    articleIds: [4],
    applies: true,
    status: "accept",
    reason: "The quote contains profanity but the policy engine marks it exempt.",
    confidence: 0.91,
    semantic: {
      semanticMeaning: "literal profanity",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "A",
      listener: "B",
      target: "B",
      victim: "B",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.91,
      notes: [],
    },
    narrative: {
      speaker: "A",
      listener: "B",
      target: "B",
      narrativeVoice: "dialogue",
      sceneType: "dialogue",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: "unknown",
      emotionalTone: "hostile",
      condemnation: true,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.92,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "كس امة",
          startOffset: 18,
          endOffset: 24,
          confidence: 0.96,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.96,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "كس امة",
      chunkContext: "chunk",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.92,
      notes: [],
    },
    exceptions: [
      {
        code: "condemnation_context",
        label: "Condemnation Context",
        applies: true,
        disposition: "allow",
        reason: "The scene condemns the profanity but does not erase the detected violation.",
        confidence: 0.88,
      },
    ],
    finding: null,
    trace: ["finding_built"],
  });

  const findings = mapLegalDecisionToFindings({
    decision: legalDecision,
    reasonedDecision: {
      reasoning: "The profanity is detected and preserved for policy review.",
      alternativeInterpretations: [],
      confidence: 0.91,
      articleEvaluations: [
        {
          articleId: 4,
          status: "PASS",
          evidence: ["كس امة"],
          reason: "The profanity is explicitly quoted.",
          confidence: 0.91,
        },
      ],
      supportingEvidence: ["كس امة"],
      contradictingEvidence: [],
      applicableArticles: [4],
      rejectedArticles: [],
      riskAnalysis: "Low ambiguity.",
      narrativeAnalysis: "The scene is condemnatory, so policy marks it exempt after detection.",
      humanLikeExplanation: "The finding should still exist even if exempted.",
      recommendation: "RETURN VIOLATION",
    },
    chunkStart: 0,
    chunkEnd: 24,
    startLine: 1,
    endLine: 1,
    diagnostics: {
      engineVersion: "v3",
      providerName: "openai",
      modelName: "gpt-4.1",
      modelVersion: "test",
      rawResponseHash: "raw",
      responseId: "response-2",
      responseTimestamp: "2026-07-16T00:00:00.000Z",
      promptHash: "prompt",
      semanticHash: "semantic",
      legalHash: "legal",
      executionSignatureHash: "execution",
      stageHashes: [],
      stageTimings: [],
      subjectModuleId: "v4_11_profanity",
      chunkHash: "chunk",
      findingCount: 1,
    } as never,
  });

  assert.equal(findings.length, 1);
  assert.equal(findings[0].article_id, 4);
  assert.equal(findings[0].policy_links?.[0]?.role, "exception_applied");
  console.log("✓ policy-applied profanity findings are preserved");
}

function testMultipleEvidenceItemsYieldMultipleFindings(): void {
  const legalDecision = createLegalDecision({
    moduleId: "v4_11_profanity",
    moduleTitle: "الألفاظ النابية",
    articleIds: [4],
    applies: true,
    status: "accept",
    reason: "The quote contains multiple distinct profanity sentences.",
    confidence: 0.93,
    semantic: {
      semanticMeaning: "literal profanity",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "A",
      listener: "B",
      target: "B",
      victim: "B",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.93,
      notes: [],
    },
    narrative: {
      speaker: "A",
      listener: "B",
      target: "B",
      narrativeVoice: "dialogue",
      sceneType: "dialogue",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: "unknown",
      emotionalTone: "hostile",
      condemnation: false,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.93,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "كس امة",
          startOffset: 10,
          endOffset: 16,
          confidence: 0.96,
          source: "chunk",
          notes: [],
        },
        {
          text: "يا حمار",
          startOffset: 18,
          endOffset: 24,
          confidence: 0.95,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.96,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "كس امة | يا حمار",
      chunkContext: "chunk",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.93,
      notes: [],
    },
    exceptions: [],
    finding: null,
    trace: ["finding_built"],
  });

  const findings = mapLegalDecisionToFindings({
    decision: legalDecision,
    reasonedDecision: {
      reasoning: "The decision contains two distinct profanity evidence items.",
      alternativeInterpretations: [],
      confidence: 0.93,
      articleEvaluations: [
        {
          articleId: 4,
          status: "PASS",
          evidence: ["كس امة", "يا حمار"],
          reason: "Both quotes are explicit profanity.",
          confidence: 0.93,
        },
      ],
      supportingEvidence: ["كس امة", "يا حمار"],
      contradictingEvidence: [],
      applicableArticles: [4],
      rejectedArticles: [],
      riskAnalysis: "Low ambiguity.",
      narrativeAnalysis: "Two separate explicit insults.",
      humanLikeExplanation: "Each sentence should become its own finding.",
      recommendation: "RETURN VIOLATION",
    },
    chunkStart: 0,
    chunkEnd: 24,
    startLine: 1,
    endLine: 1,
    diagnostics: {
      engineVersion: "v3",
      providerName: "openai",
      modelName: "gpt-4.1",
      modelVersion: "test",
      rawResponseHash: "raw",
      responseId: "response-4",
      responseTimestamp: "2026-07-16T00:00:00.000Z",
      promptHash: "prompt",
      semanticHash: "semantic",
      legalHash: "legal",
      executionSignatureHash: "execution",
      stageHashes: [],
      stageTimings: [],
      subjectModuleId: "v4_11_profanity",
      chunkHash: "chunk",
      findingCount: 2,
    } as never,
  });

  assert.equal(findings.length, 2);
  assert.deepEqual(findings.map((finding) => finding.evidence_snippet), ["كس امة", "يا حمار"]);
  console.log("✓ multiple evidence items yield multiple findings");
}

function testSmallestGroundedEvidenceSpanIsPreserved(): void {
  const legalDecision = createLegalDecision({
    moduleId: "v4_11_profanity",
    moduleTitle: "الألفاظ النابية",
    articleIds: [4],
    applies: true,
    status: "accept",
    reason: "The short quoted insult should be preserved as the display snippet.",
    confidence: 0.92,
    semantic: {
      semanticMeaning: "literal profanity",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "A",
      listener: "B",
      target: "B",
      victim: "B",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.92,
      notes: [],
    },
    narrative: {
      speaker: "A",
      listener: "B",
      target: "B",
      narrativeVoice: "dialogue",
      sceneType: "dialogue",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: "unknown",
      emotionalTone: "hostile",
      condemnation: false,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.92,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "الجارة قالت: كس امة",
          startOffset: 12,
          endOffset: 30,
          confidence: 0.94,
          source: "chunk",
          notes: [],
        },
        {
          text: "كس امة",
          startOffset: 24,
          endOffset: 30,
          confidence: 0.99,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.96,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "الجارة قالت: كس امة",
      chunkContext: "chunk",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.92,
      notes: [],
    },
    exceptions: [],
    finding: createLegalFinding({
      findingKey: "v4_11_profanity:12-30:accept",
      moduleId: "v4_11_profanity",
      moduleTitle: "الألفاظ النابية",
      articleIds: [4],
      status: "accept",
      reason: "The short quoted insult should be preserved as the display snippet.",
      confidence: 0.92,
      semantic: {
        semanticMeaning: "literal profanity",
        narrativeIntent: "attack",
        conversationRole: "speaker",
        sceneRole: "dialogue",
        speaker: "A",
        listener: "B",
        target: "B",
        victim: "B",
        emotion: "hostile",
        riskContext: "high",
        confidence: 0.92,
        notes: [],
      },
      narrative: {
        speaker: "A",
        listener: "B",
        target: "B",
        narrativeVoice: "dialogue",
        sceneType: "dialogue",
        narrativeIntent: "attack",
        storyPosition: "middle",
        relationship: "unknown",
        emotionalTone: "hostile",
        condemnation: false,
        approval: false,
        neutrality: false,
        historicalContext: false,
        dream: false,
        flashback: false,
        comedy: false,
        satire: false,
        threat: false,
        instruction: false,
        news: false,
        documentary: false,
        dialogue: true,
        narration: false,
        sceneDescription: false,
        confidence: 0.92,
        notes: [],
      },
      evidence: {
        text: "الجارة قالت: كس امة",
        startOffset: 12,
        endOffset: 30,
        confidence: 0.94,
        source: "chunk",
        notes: [],
      },
      context: {
        storyMemory: null,
        sceneMemory: null,
        localContext: "الجارة قالت: كس امة",
        chunkContext: "chunk",
        neighboringSentences: [],
        narrativeContext: "dialogue",
        confidence: 0.92,
        notes: [],
      },
      exceptionCodes: [],
    }),
    trace: ["finding_built"],
  });

  const findings = mapLegalDecisionToFindings({
    decision: legalDecision,
    reasonedDecision: {
      reasoning: "The short quoted insult is the real trigger.",
      alternativeInterpretations: [],
      confidence: 0.92,
      articleEvaluations: [
        {
          articleId: 4,
          status: "PASS",
          evidence: ["كس امة"],
          reason: "The short quote is the grounded trigger.",
          confidence: 0.92,
        },
      ],
      supportingEvidence: ["كس امة"],
      contradictingEvidence: [],
      applicableArticles: [4],
      rejectedArticles: [],
      riskAnalysis: "Low ambiguity.",
      narrativeAnalysis: "The exact insult is the relevant span.",
      humanLikeExplanation: "Only the short grounded span should be displayed.",
      recommendation: "RETURN VIOLATION",
    },
    chunkStart: 0,
    chunkEnd: 30,
    startLine: 1,
    endLine: 1,
    diagnostics: {
      engineVersion: "v3",
      providerName: "openai",
      modelName: "gpt-4.1",
      modelVersion: "test",
      rawResponseHash: "raw",
      responseId: "response-5",
      responseTimestamp: "2026-07-16T00:00:00.000Z",
      promptHash: "prompt",
      semanticHash: "semantic",
      legalHash: "legal",
      executionSignatureHash: "execution",
      stageHashes: [],
      stageTimings: [],
      subjectModuleId: "v4_11_profanity",
      chunkHash: "chunk",
      findingCount: 1,
    } as never,
    gcamMapping: {
      status: "UNMAPPED",
      articleId: null,
      articleNumber: null,
      articleTitleAr: null,
      atomId: null,
      atomNumber: null,
      atomTitleAr: null,
      findingTitle: "UNMAPPED",
      findingCategory: "UNMAPPED",
      reviewerExplanation: "No official GCAM mapping exists. A mapping debt record was created instead of guessing.",
      supportingEvidence: ["كس امة"],
      matchedRuleId: null,
      matchedArticleMappingId: null,
      matchedAtomMappingId: null,
      confidence: 0.92,
      mappingDebt: [],
      hash: "hash",
    } as never,
  });

  assert.equal(findings.length, 1);
  assert.equal(findings[0].evidence_snippet, "كس امة");
  assert.equal(findings[0].start_offset_global, 24);
  assert.equal(findings[0].end_offset_global, 30);
  console.log("✓ finding mapper preserves the smallest grounded evidence span");
}

function main(): void {
  testLegalArticleWinsOverGcamMapping();
  testArticleFourteenResolvesFromPolicyCatalog();
  testPolicyAppliedFindingIsPreserved();
  testMultipleEvidenceItemsYieldMultipleFindings();
  testSmallestGroundedEvidenceSpanIsPreserved();
  console.log("\nAll V3 finding mapper tests passed.");
}

main();
