/**
 * Regression test for the V3 finding mapper.
 * Run: node --import tsx apps/worker/src/analysisEngineV3/runtime/findingMapper.test.ts
 */
import { strict as assert } from "node:assert";

import { createLegalDecision, createLegalFinding } from "../legal/legalResult.js";
import { mapLegalDecisionToFindings } from "./findingMapper.js";

function testLegalArticleWinsOverGcamMapping(): void {
  const legalDecision = createLegalDecision({
    moduleId: "v3_01_religion",
    moduleTitle: "Religion Reviewer",
    articleIds: [8],
    applies: true,
    status: "accept",
    reason: "The quote directly attacks religion.",
    confidence: 0.94,
    semantic: {
      semanticMeaning: "Direct religious insult.",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "speaker",
      listener: "listener",
      target: "target",
      victim: "victim",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.95,
      notes: [],
    },
    narrative: {
      speaker: "speaker",
      listener: "listener",
      target: "target",
      narrativeVoice: "dialogue",
      sceneType: "dialogue",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: "unknown",
      emotionalTone: "hostile",
      condemnation: false,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.95,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "هذا الكلام إساءة دينية",
          startOffset: 10,
          endOffset: 20,
          confidence: 0.94,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.94,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "هذا الكلام إساءة دينية",
      chunkContext: "chunk",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.94,
      notes: [],
    },
    exceptions: [],
    finding: createLegalFinding({
      findingKey: "v3_01_religion:10-20:8:هذا الكلام إساءة دينية:accept",
      moduleId: "v3_01_religion",
      moduleTitle: "Religion Reviewer",
      articleIds: [8],
      status: "accept",
      reason: "The quote directly attacks religion.",
      confidence: 0.94,
      semantic: {
        semanticMeaning: "Direct religious insult.",
        narrativeIntent: "attack",
        conversationRole: "speaker",
        sceneRole: "dialogue",
        speaker: "speaker",
        listener: "listener",
        target: "target",
        victim: "victim",
        emotion: "hostile",
        riskContext: "high",
        confidence: 0.95,
        notes: [],
      },
      narrative: {
        speaker: "speaker",
        listener: "listener",
        target: "target",
        narrativeVoice: "dialogue",
        sceneType: "dialogue",
        narrativeIntent: "attack",
        storyPosition: "middle",
        relationship: "unknown",
        emotionalTone: "hostile",
        condemnation: false,
        approval: false,
        neutrality: false,
        historicalContext: false,
        dream: false,
        flashback: false,
        comedy: false,
        satire: false,
        threat: false,
        instruction: false,
        news: false,
        documentary: false,
        dialogue: true,
        narration: false,
        sceneDescription: false,
        confidence: 0.95,
        notes: [],
      },
      evidence: {
        text: "هذا الكلام إساءة دينية",
        startOffset: 10,
        endOffset: 20,
        confidence: 0.94,
        source: "chunk",
        notes: [],
      },
      context: {
        storyMemory: null,
        sceneMemory: null,
        localContext: "هذا الكلام إساءة دينية",
        chunkContext: "chunk",
        neighboringSentences: [],
        narrativeContext: "dialogue",
        confidence: 0.94,
        notes: [],
      },
      exceptionCodes: [],
    }),
    trace: ["finding_built"],
  });

  const findings = mapLegalDecisionToFindings({
    decision: legalDecision,
    chunkStart: 0,
    chunkEnd: 20,
    startLine: 1,
    endLine: 1,
    diagnostics: {
      engineVersion: "v3",
      providerName: "openai",
      modelName: "gpt-4.1",
      modelVersion: "test",
      rawResponseHash: "raw",
      responseId: "response-1",
      responseTimestamp: "2026-07-16T00:00:00.000Z",
      promptHash: "prompt",
      semanticHash: "semantic",
      legalHash: "legal",
      executionSignatureHash: "execution",
      stageHashes: [],
      stageTimings: [],
      subjectModuleId: "v3_01_religion",
      chunkHash: "chunk",
      findingCount: 1,
    } as never,
    gcamMapping: {
      status: "MAPPED",
      articleId: 14,
      articleNumber: "14",
      articleTitleAr: "مادة 14",
      atomId: "14-1",
      atomNumber: "14.1",
      atomTitleAr: "Atom 14.1",
      findingTitle: "Mapped title",
      findingCategory: "security",
      reviewerExplanation: "Mapped explanation",
      supportingEvidence: ["هذا الكلام إساءة دينية"],
      matchedRuleId: "rule-1",
      matchedArticleMappingId: "article-mapping-1",
      matchedAtomMappingId: "atom-mapping-1",
      confidence: 0.9,
      mappingDebt: [],
      hash: "hash",
    },
  });

  assert.equal(findings.length, 1);
  assert.equal(findings[0].article_id, 8);
  assert.notEqual(findings[0].atom_id, "14-1");
  console.log("✓ legal article wins over GCAM mapping when the mapper disagrees");
}

function main(): void {
  testLegalArticleWinsOverGcamMapping();
  console.log("\nAll V3 finding mapper tests passed.");
}

main();
