import { strict as assert } from "node:assert";
import { createLegalDecision } from "../legal/legalDecision.js";
import { createLegalFinding } from "../legal/legalResult.js";
import { buildCanonicalArticleOwnershipMap } from "../reviewerKnowledge/reviewerKnowledgeRegistry.js";
import { createDefaultReviewerKnowledgeRegistry } from "../reviewerKnowledge/reviewerKnowledgeRegistry.js";
import { validateReviewerScope } from "./reviewerScopeValidator.js";

function makeRouting(): Parameters<typeof validateReviewerScope>[0]["routing"] {
  return {
    selectedReviewerIds: ["v4_11_profanity"],
    selectedReviewerLabels: ["Profanity Reviewer"],
    selectedReviewerPackIds: ["v3_00_universal", "v4_11_profanity"],
    selectedAcademyFolders: ["universal", "profanity"],
    rejectedReviewerIds: ["v3_01_religion"],
    rejectedReviewerLabels: ["Religion Reviewer"],
    loadedAcademyCount: 2,
    skippedAcademyCount: 1,
    knowledgeReductionPercent: 50,
    routingConfidence: 0.91,
    routingReason: "Profanity signal is dominant.",
    lowConfidence: false,
    reviewerScores: [],
  };
}

function makeCanonicalOwnershipMap(): Parameters<typeof validateReviewerScope>[0]["canonicalArticleOwnershipByArticleId"] {
  return buildCanonicalArticleOwnershipMap(createDefaultReviewerKnowledgeRegistry());
}

function testScopeAcceptance(): void {
  const decision = createLegalDecision({
    moduleId: "v4_11_profanity",
    moduleTitle: "الألفاظ النابية",
    articleIds: [4],
    applies: true,
    status: "accept",
    reason: "Scope-matched profanity finding.",
    confidence: 0.91,
    semantic: {
      semanticMeaning: "literal profanity",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "A",
      listener: "B",
      target: "B",
      victim: "B",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.91,
      notes: [],
    },
    narrative: {
      speaker: "A",
      listener: "B",
      target: "B",
      narrativeVoice: "dialogue",
      sceneType: "dialogue scene",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: null,
      emotionalTone: "hostile",
      condemnation: false,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.9,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "يا كلب",
          startOffset: 4,
          endOffset: 10,
          confidence: 0.95,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.95,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "يا كلب",
      chunkContext: "chunk-1",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.9,
      notes: [],
    },
    exceptions: [],
    finding: createLegalFinding({
      findingKey: "v4_11_profanity:4-10:accept",
      moduleId: "v4_11_profanity",
      moduleTitle: "الألفاظ النابية",
      articleIds: [4],
      status: "accept",
      reason: "Scope-matched profanity finding.",
      confidence: 0.91,
      semantic: {
        semanticMeaning: "literal profanity",
        narrativeIntent: "attack",
        conversationRole: "speaker",
        sceneRole: "dialogue",
        speaker: "A",
        listener: "B",
        target: "B",
        victim: "B",
        emotion: "hostile",
        riskContext: "high",
        confidence: 0.91,
        notes: [],
      },
      narrative: {
        speaker: "A",
        listener: "B",
        target: "B",
        narrativeVoice: "dialogue",
        sceneType: "dialogue scene",
        narrativeIntent: "attack",
        storyPosition: "middle",
        relationship: null,
        emotionalTone: "hostile",
        condemnation: false,
        approval: false,
        neutrality: false,
        historicalContext: false,
        dream: false,
        flashback: false,
        comedy: false,
        satire: false,
        threat: false,
        instruction: false,
        news: false,
        documentary: false,
        dialogue: true,
        narration: false,
        sceneDescription: false,
        confidence: 0.9,
        notes: [],
      },
      evidence: {
        text: "يا كلب",
        startOffset: 4,
        endOffset: 10,
        confidence: 0.95,
        source: "chunk",
        notes: [],
      },
      context: {
        storyMemory: null,
        sceneMemory: null,
        localContext: "يا كلب",
        chunkContext: "chunk-1",
        neighboringSentences: [],
        narrativeContext: "dialogue",
        confidence: 0.9,
        notes: [],
      },
      exceptionCodes: [],
    }),
    trace: ["finding_built"],
  });

  const result = validateReviewerScope({
    routing: makeRouting(),
    canonicalArticleOwnershipByArticleId: makeCanonicalOwnershipMap(),
    decision,
  });

  assert.equal(result.acceptedFindingsCount, 1);
  assert.equal(result.rejectedFindingsByScopeCount, 0);
  assert.equal(result.sanitizedDecision.finding !== null, true);
  assert.equal(result.sanitizedDecision.finding?.moduleId, "v4_11_profanity");
}

function testScopeRejection(): void {
  const decision = createLegalDecision({
    moduleId: "v3_01_religion",
    moduleTitle: "المسائل الدينية الأساسية",
    articleIds: [999],
    applies: true,
    status: "accept",
    reason: "Wrong reviewer scope.",
    confidence: 0.91,
    semantic: {
      semanticMeaning: "religious insult",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "A",
      listener: "B",
      target: "B",
      victim: "B",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.91,
      notes: [],
    },
    narrative: {
      speaker: "A",
      listener: "B",
      target: "B",
      narrativeVoice: "dialogue",
      sceneType: "dialogue scene",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: null,
      emotionalTone: "hostile",
      condemnation: false,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.9,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "هذا دين باطل",
          startOffset: 4,
          endOffset: 16,
          confidence: 0.95,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.95,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "هذا دين باطل",
      chunkContext: "chunk-2",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.9,
      notes: [],
    },
    exceptions: [],
    finding: createLegalFinding({
      findingKey: "v3_01_religion:4-16:reject",
      moduleId: "v3_01_religion",
      moduleTitle: "المسائل الدينية الأساسية",
      articleIds: [999],
      status: "accept",
      reason: "Wrong reviewer scope.",
      confidence: 0.91,
      semantic: {
        semanticMeaning: "religious insult",
        narrativeIntent: "attack",
        conversationRole: "speaker",
        sceneRole: "dialogue",
        speaker: "A",
        listener: "B",
        target: "B",
        victim: "B",
        emotion: "hostile",
        riskContext: "high",
        confidence: 0.91,
        notes: [],
      },
      narrative: {
        speaker: "A",
        listener: "B",
        target: "B",
        narrativeVoice: "dialogue",
        sceneType: "dialogue scene",
        narrativeIntent: "attack",
        storyPosition: "middle",
        relationship: null,
        emotionalTone: "hostile",
        condemnation: false,
        approval: false,
        neutrality: false,
        historicalContext: false,
        dream: false,
        flashback: false,
        comedy: false,
        satire: false,
        threat: false,
        instruction: false,
        news: false,
        documentary: false,
        dialogue: true,
        narration: false,
        sceneDescription: false,
        confidence: 0.9,
        notes: [],
      },
      evidence: {
        text: "هذا دين باطل",
        startOffset: 4,
        endOffset: 16,
        confidence: 0.95,
        source: "chunk",
        notes: [],
      },
      context: {
        storyMemory: null,
        sceneMemory: null,
        localContext: "هذا دين باطل",
        chunkContext: "chunk-2",
        neighboringSentences: [],
        narrativeContext: "dialogue",
        confidence: 0.9,
        notes: [],
      },
      exceptionCodes: [],
    }),
    trace: ["finding_built"],
  });

  const result = validateReviewerScope({
    routing: makeRouting(),
    canonicalArticleOwnershipByArticleId: makeCanonicalOwnershipMap(),
    decision,
  });

  assert.equal(result.acceptedFindingsCount, 0);
  assert.equal(result.rejectedFindingsByScopeCount, 1);
  assert.equal(result.sanitizedDecision.finding, null);
  assert.equal(result.sanitizedDecision.status, "reject");
}

function testScopeReassignmentPrefersSelectedCanonicalOwner(): void {
  const decision = createLegalDecision({
    moduleId: "v3_03_security",
    moduleTitle: "National Security Reviewer",
    articleIds: [17],
    applies: true,
    status: "accept",
    reason: "The quote directly urges overthrow.",
    confidence: 0.95,
    semantic: {
      semanticMeaning: "Direct overthrow incitement.",
      narrativeIntent: "attack",
      conversationRole: "speaker",
      sceneRole: "dialogue",
      speaker: "speaker",
      listener: "listener",
      target: "target",
      victim: "victim",
      emotion: "hostile",
      riskContext: "high",
      confidence: 0.95,
      notes: [],
    },
    narrative: {
      speaker: "speaker",
      listener: "listener",
      target: "target",
      narrativeVoice: "dialogue",
      sceneType: "dialogue scene",
      narrativeIntent: "attack",
      storyPosition: "middle",
      relationship: null,
      emotionalTone: "hostile",
      condemnation: false,
      approval: false,
      neutrality: false,
      historicalContext: false,
      dream: false,
      flashback: false,
      comedy: false,
      satire: false,
      threat: false,
      instruction: false,
      news: false,
      documentary: false,
      dialogue: true,
      narration: false,
      sceneDescription: false,
      confidence: 0.95,
      notes: [],
    },
    evidence: {
      candidates: [
        {
          text: "سنسقط النظام الليلة",
          startOffset: 12,
          endOffset: 30,
          confidence: 0.96,
          source: "chunk",
          notes: [],
        },
      ],
      primaryCandidateIndex: 0,
      admissible: true,
      confidence: 0.96,
      notes: [],
    },
    context: {
      storyMemory: null,
      sceneMemory: null,
      localContext: "سنسقط النظام الليلة",
      chunkContext: "chunk-14",
      neighboringSentences: [],
      narrativeContext: "dialogue",
      confidence: 0.95,
      notes: [],
    },
    exceptions: [],
    finding: createLegalFinding({
      findingKey: "v3_03_security:17",
      moduleId: "v3_03_security",
      moduleTitle: "National Security Reviewer",
      articleIds: [17],
      status: "accept",
      reason: "The quote directly urges overthrow.",
      confidence: 0.95,
      semantic: {
        semanticMeaning: "Direct overthrow incitement.",
        narrativeIntent: "attack",
        conversationRole: "speaker",
        sceneRole: "dialogue",
        speaker: "speaker",
        listener: "listener",
        target: "target",
        victim: "victim",
        emotion: "hostile",
        riskContext: "high",
        confidence: 0.95,
        notes: [],
      },
      narrative: {
        speaker: "speaker",
        listener: "listener",
        target: "target",
        narrativeVoice: "dialogue",
        sceneType: "dialogue scene",
        narrativeIntent: "attack",
        storyPosition: "middle",
        relationship: null,
        emotionalTone: "hostile",
        condemnation: false,
        approval: false,
        neutrality: false,
        historicalContext: false,
        dream: false,
        flashback: false,
        comedy: false,
        satire: false,
        threat: false,
        instruction: false,
        news: false,
        documentary: false,
        dialogue: true,
        narration: false,
        sceneDescription: false,
        confidence: 0.95,
        notes: [],
      },
      evidence: {
        text: "سنسقط النظام الليلة",
        startOffset: 12,
        endOffset: 30,
        confidence: 0.96,
        source: "chunk",
        notes: [],
      },
      context: {
        storyMemory: null,
        sceneMemory: null,
        localContext: "سنسقط النظام الليلة",
        chunkContext: "chunk-17",
        neighboringSentences: [],
        narrativeContext: "dialogue",
        confidence: 0.95,
        notes: [],
      },
      exceptionCodes: [],
    }),
    trace: ["finding_built"],
  });

  const result = validateReviewerScope({
    routing: {
      selectedReviewerIds: ["v3_04_politics"],
      selectedReviewerLabels: ["Politics Reviewer"],
      selectedReviewerPackIds: ["v3_00_universal", "v3_04_politics"],
      selectedAcademyFolders: ["universal", "politics"],
      rejectedReviewerIds: ["v3_03_security"],
      rejectedReviewerLabels: ["National Security Reviewer"],
      loadedAcademyCount: 2,
      skippedAcademyCount: 1,
      knowledgeReductionPercent: 50,
      routingConfidence: 0.87,
      routingReason: "The evidence supports a politics case.",
      lowConfidence: false,
      reviewerScores: [],
    },
    canonicalArticleOwnershipByArticleId: makeCanonicalOwnershipMap(),
    decision,
  });

  assert.equal(result.acceptedFindingsCount, 1);
  assert.equal(result.rejectedFindingsByScopeCount, 0);
  assert.equal(result.acceptedFindings[0]?.moduleId, "v3_04_politics");
  console.log("✓ reviewer scope validator reassigns overlapping ownership to the selected canonical reviewer");
}

function main(): void {
  testScopeAcceptance();
  testScopeRejection();
  testScopeReassignmentPrefersSelectedCanonicalOwner();
  console.log("✓ reviewer scope validator enforces reviewer ownership");
}

main();
