import { create } from 'zustand';

type Lang = 'ar' | 'en';

const translations = {
  ar: {
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    rememberMe: 'تذكرني',
    overview: 'نظرة عامة',
    glossary: 'المصطلحات',
    clients: 'العملاء (الشركات)',
    accessControl: 'إدارة الصلاحيات',
    certificates: 'الشهادات',
    reports: 'التقارير',
    settings: 'الإعدادات',
    users: 'المستخدمين',
    addUser: 'إضافة مستخدم جديد',
    name: 'الاسم',
    role: 'الدور',
    permissions: 'الصلاحيات',
    status: 'الحالة',
    search: 'بحث...',
    active: 'نشط',
    disabled: 'معطل',
    cancel: 'إلغاء',
    save: 'حفظ',
    accessDenied: 'غير مصرح لك بالدخول',
    backToHome: 'العودة للرئيسية',
    superAdmin: 'مدير النظام',
    admin: 'مشرف',
    regulator: 'مراقب',
    addNewClient: 'إضافة عميل جديد',
    totalClients: 'إجمالي العملاء',
    registeredScripts: 'النصوص المسجلة',
    pendingScripts: 'النصوص المعلقة',
    approvedScripts: 'النصوص المعتمدة',
    representative: 'الممثل',
    registrationDate: 'تاريخ التسجيل',
    scriptsCount: 'عدد النصوص',
    clientDetails: 'تفاصيل العميل',
    searchClients: 'ابحث عن اسم الشركة (عربي / انجليزي)',
    editClient: 'تعديل بيانات العميل',
    editData: 'تعديل البيانات',
    clientUpdated: 'تم تحديث البيانات بنجاح',
    reportViewerTitle: 'تقرير المواءمة التنظيمية للنصوص',
    pass: 'مجاز رقابياً',
    reject: 'مرفوض - مخالفات حرجة',
    reviewRequired: 'يتطلب مراجعة بشرية',
    refresh: 'تحديث',
    printReport: 'طباعة التقرير (PDF)',
    exportReport: 'إصدار التقرير',
    cleanLog: 'سجل نظيف',
    overriddenOk: 'تم التجاوز (مقبول)',
    hiddenOwner: 'مخفية عن المالك',
    editStatus: 'تعديل الحالة / تجاوز',
    restoreOriginal: 'استعادة للأصل',
    updateOverride: 'تحديث التجاوز',
    overrideReason: 'تبرير التجاوز:',
    byUser: 'بواسطة:',
    findingDescription: 'وصف الملاحظة',
    manualFinding: 'ملاحظة يدوية',
    findingSourceAi: 'تحليل آلي',
    findingSourceManual: 'ملاحظة يدوية',
    findingSourceGlossary: 'مطابقة قاموس',
    lexiconSignals: 'إشارات القاموس (للمراجعة البشرية)',
    domainA: 'السيادة والأسس الوطنية',
    domainB: 'الحقوق والكرامة والحماية الإنسانية',
    domainC: 'القيم الدينية والأخلاقية',
    domainD: 'المحظورات والسلوكيات الضارة',
    domainE: 'عام (أخرى)',
    unknownLocation: 'مكان غير محدد',
    page: 'صفحة',
    scene: 'مشهد',
    low: 'منخفض',
    medium: 'متوسط',
    high: 'عالي',
    critical: 'حرج',
    // Overview
    pendingTasks: 'المهام المعلقة',
    viewTasks: 'عرض المهام',
    scriptsInReview: 'نصوص قيد المراجعة',
    openScripts: 'فتح النصوص',
    reportsThisMonth: 'التقارير هذا الشهر',
    goToReports: 'الانتقال للتقارير',
    highCriticalFindings: 'مخالفات عالية/حرجة',
    totalReports: 'إجمالي التقارير',
    approved: 'معتمدة',
    rejected: 'مرفوضة',
    reportsSubtitle: 'عرض تقارير المراجعة والامتثال',
    reportId: 'رقم التقرير',
    company: 'الشركة',
    scriptTitle: 'اسم النص',
    type: 'النوع',
    reportDate: 'تاريخ التقرير',
    reviewer: 'المنفذ / المراجع',
    decision: 'القرار',
    totalFindings: 'إجمالي الملاحظات',
    open: 'فتح',
    openHtml: 'فتح HTML',
    viewResults: 'عرض النتائج',
    scriptsByStatus: 'توزيع النصوص حسب الحالة',
    findingsBySeverity: 'توزيع المخالفات حسب الخطورة',
    quickActions: 'إجراءات سريعة',
    addClientAction: 'إضافة شركة جديدة',
    uploadScriptAction: 'رفع نص جديد',
    assignTaskAction: 'إسناد مهمة',
    startAnalysisAction: 'بدء التحليل',
    generateReportAction: 'إصدار تقرير',
    addTermAction: 'إضافة مصطلح للقاموس',
    recentActivity: 'النشاطات الأخيرة',
    showAll: 'عرض الكل',
    auditLog: 'سجل التدقيق',
    auditWhat: 'الإجراء',
    auditWho: 'المستخدم',
    auditWhen: 'الوقت',
    auditTarget: 'الهدف',
    auditResult: 'النتيجة',
    auditMetadata: 'البيانات الوصفية',
    exportCsv: 'تصدير CSV',
    exportPdf: 'تصدير PDF',
    filterByDate: 'التاريخ',
    filterByUser: 'المستخدم',
    filterByEventType: 'نوع الحدث',
    filterByTargetType: 'نوع الهدف',
    filterByResult: 'النتيجة',
    searchKeyword: 'بحث',
    myQueue: 'قائمتي',
    openScript: 'فتح النص',
    draft: 'مسودة',
    assigned: 'تم الإسناد',
    analysis_running: 'جاري التحليل',
    review_required: 'يتطلب المراجعة',
    completed: 'مكتمل',
    // Glossary
    lexiconManagement: 'إدارة قاموس المصطلحات العامية',
    totalTerms: 'إجمالي المصطلحات',
    softSignals: 'إشارات ضعيفة',
    softSignalsSub: 'تفسيرية (AI يقرر)',
    mandatoryViolations: 'مخالفات إلزامية',
    mandatoryViolationsSub: 'دائماً مخالفة',
    allCategories: 'جميع التصنيفات',
    allSeverities: 'جميع المستويات',
    allModes: 'جميع الأوضاع',
    addTerm: 'إضافة مصطلح',
    importCsv: 'استيراد CSV',
    term: 'المصطلح',
    termType: 'النوع',
    category: 'التصنيف',
    enforcementMode: 'وضع التطبيق',
    article: 'المادة',
    actions: 'الإجراءات',
    termExists: 'هذا المصطلح موجود مسبقاً في القاموس',
    word: 'كلمة',
    phrase: 'عبارة',
    regex: 'نمط',
    profanity: 'ألفاظ نابية',
    sexual: 'إيحاءات',
    violence: 'عنف',
    drugs: 'مخدرات',
    gambling: 'قمار',
    blasphemy: 'تجديف',
    discrimination: 'تمييز',
    misogyny: 'كراهية النساء',
    humiliation: 'إهانة',
    threat: 'تهديد',
    other: 'أخرى',
    severity: 'الخطورة',
    severityFloor: 'الحد الأدنى للخطورة',
    description: 'الوصف',
    exampleUsage: 'مثال على الاستخدام',
    gcamArticleId: 'رقم المادة (GCAM)',
    gcamAtomId: 'رقم البند (اختياري)',
    gcamArticleTitle: 'عنوان المادة بالعربية',
    saveTerm: 'حفظ المصطلح',
    // Settings
    myAccount: 'حسابي',
    platformSettings: 'إعدادات المنصة',
    security: 'الأمان',
    brandingReports: 'العلامة والتقارير',
    featureFlags: 'ميزات تجريبية',
    profile: 'الملف الشخصي',
    fullName: 'الاسم الكامل',
    preferredLanguage: 'اللغة المفضلة',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    signOut: 'تسجيل الخروج',
    defaultLanguage: 'اللغة الافتراضية',
    defaultReportMode: 'وضع التقرير الافتراضي',
    inApp: 'داخل التطبيق',
    standaloneHtml: 'HTML مستقل',
    both: 'كلاهما',
    dateFormat: 'صيغة التاريخ',
    versioningBehavior: 'سلوك الإصدارات',
    createVersionOnReplace: 'إنشاء إصدار جديد عند استبدال الملف',
    requireOverrideReason: 'طلب سبب عند التجاوز',
    sessionTimeout: 'مهلة الجلسة (دقائق)',
    forceRelogin: 'فرض تسجيل الدخول بعد المهلة',
    auditLogRetention: 'الاحتفاظ بسجل التدقيق (أيام)',
    passwordPolicy: 'سياسة كلمة المرور',
    passwordPolicyDesc: '8 أحرف على الأقل، تتضمن أحرف كبيرة وصغيرة وأرقام.',
    orgNameAr: 'اسم المنظمة (عربي)',
    orgNameEn: 'اسم المنظمة (إنجليزي)',
    logoUpload: 'شعار المنظمة (رابط URL)',
    footerNoteAr: 'ملاحظة التذييل (عربي)',
    footerNoteEn: 'ملاحظة التذييل (إنجليزي)',
    showDecisionBadge: 'عرض شارة القرار في التقرير المطبوع',
    paperSize: 'حجم الورق الافتراضي',
    enableCertificates: 'تفعيل الشهادات',
    enableLexiconCsv: 'تفعيل استيراد/تصدير القاموس',
    enableHiddenOverrides: 'تفعيل الإخفاء عن المالك (تجاوز)',
    saveChanges: 'حفظ التغييرات',
    settingsUpdated: 'تم حفظ الإعدادات بنجاح',
    featureCertDesc: 'تفعيل قسم إدارة الشهادات في القائمة الجانبية.',
    featureLexiconDesc: 'السماح باستيراد وتصدير مصطلحات القاموس عبر ملفات CSV.',
    featureHiddenDesc: 'السماح للمراقبين بإخفاء الملاحظات عن مالك النص.'
  },
  en: {
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember Me',
    overview: 'Overview',
    glossary: 'Glossary',
    clients: 'Clients (Companies)',
    accessControl: 'Access Control',
    certificates: 'Certificates',
    reports: 'Reports',
    settings: 'Settings',
    users: 'Users',
    addUser: 'Add New User',
    name: 'Name',
    role: 'Role',
    permissions: 'Permissions',
    status: 'Status',
    search: 'Search...',
    active: 'Active',
    disabled: 'Disabled',
    cancel: 'Cancel',
    save: 'Save',
    accessDenied: 'Access Denied',
    backToHome: 'Back to Home',
    superAdmin: 'Super Admin',
    admin: 'Admin',
    regulator: 'Regulator',
    addNewClient: 'Add New Client',
    totalClients: 'Total Clients',
    registeredScripts: 'Registered Scripts',
    pendingScripts: 'Pending Scripts',
    approvedScripts: 'Approved Scripts',
    representative: 'Representative',
    registrationDate: 'Registration Date',
    scriptsCount: 'Scripts Count',
    clientDetails: 'Client Details',
    searchClients: 'Search company name (Arabic / English)',
    editClient: 'Edit Client Data',
    editData: 'Edit Data',
    clientUpdated: 'Client updated successfully',
    reportViewerTitle: 'Regulatory Alignment Report',
    pass: 'PASS',
    reject: 'REJECT - Critical Violations',
    reviewRequired: 'REVIEW REQUIRED',
    refresh: 'Refresh',
    printReport: 'Print Report (PDF)',
    exportReport: 'Export Report',
    cleanLog: 'Clean Log',
    overriddenOk: 'Overridden (Accepted)',
    hiddenOwner: 'Hidden from Owner',
    editStatus: 'Edit Status / Override',
    restoreOriginal: 'Restore Original',
    updateOverride: 'Update Override',
    overrideReason: 'Override Reason:',
    byUser: 'By:',
    findingDescription: 'Finding Description',
    manualFinding: 'Manual Finding',
    findingSourceAi: 'AI Analysis',
    findingSourceManual: 'Manual Note',
    findingSourceGlossary: 'Glossary Match',
    lexiconSignals: 'Lexicon Signals (Human Review)',
    domainA: 'National Sovereignty & Foundations',
    domainB: 'Rights, Dignity & Human Protection',
    domainC: 'Religious & Moral Values',
    domainD: 'Prohibitions & Harmful Behaviors',
    domainE: 'General (Other)',
    unknownLocation: 'Unknown location',
    page: 'Page',
    scene: 'Scene',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
    // Overview
    pendingTasks: 'Pending Tasks',
    viewTasks: 'View Tasks',
    scriptsInReview: 'Scripts In Review',
    openScripts: 'Open Scripts',
    reportsThisMonth: 'Reports This Month',
    goToReports: 'Go to Reports',
    highCriticalFindings: 'High/Critical Findings',
    totalReports: 'Total Reports',
    approved: 'Approved',
    rejected: 'Rejected',
    reportsSubtitle: 'View Compliance and Review Reports',
    reportId: 'Report ID',
    company: 'Company',
    scriptTitle: 'Script Title',
    type: 'Type',
    reportDate: 'Report Date',
    reviewer: 'Reviewer / Assignee',
    decision: 'Decision',
    totalFindings: 'Total Findings',
    open: 'Open',
    openHtml: 'Open HTML',
    viewResults: 'View Results',
    scriptsByStatus: 'Scripts by Status',
    findingsBySeverity: 'Findings by Severity',
    quickActions: 'Quick Actions',
    addClientAction: 'Add New Client',
    uploadScriptAction: 'Upload New Script',
    assignTaskAction: 'Assign Task',
    startAnalysisAction: 'Start Analysis',
    generateReportAction: 'Generate Report',
    addTermAction: 'Add Term to Lexicon',
    recentActivity: 'Recent Activity',
    showAll: 'Show all',
    auditLog: 'Audit Log',
    auditWhat: 'What',
    auditWho: 'Who',
    auditWhen: 'When',
    auditTarget: 'Target',
    auditResult: 'Result',
    auditMetadata: 'Metadata',
    exportCsv: 'Export CSV',
    exportPdf: 'Export PDF',
    filterByDate: 'Date',
    filterByUser: 'User',
    filterByEventType: 'Event type',
    filterByTargetType: 'Target type',
    filterByResult: 'Result',
    searchKeyword: 'Search',
    myQueue: 'My Queue',
    openScript: 'Open Script',
    draft: 'Draft',
    assigned: 'Assigned',
    analysis_running: 'Analysis Running',
    review_required: 'Review Required',
    completed: 'Completed',
    // Glossary
    lexiconManagement: 'Slang Lexicon Management',
    totalTerms: 'Total Terms',
    softSignals: 'Soft Signals',
    softSignalsSub: 'Interpretive (AI decides)',
    mandatoryViolations: 'Mandatory Violations',
    mandatoryViolationsSub: 'Always a violation',
    allCategories: 'All Categories',
    allSeverities: 'All Severities',
    allModes: 'All Modes',
    addTerm: 'Add Term',
    importCsv: 'Import CSV',
    term: 'Term',
    termType: 'Type',
    category: 'Category',
    enforcementMode: 'Enforcement Mode',
    article: 'Article',
    actions: 'Actions',
    termExists: 'This term already exists in the lexicon',
    word: 'Word',
    phrase: 'Phrase',
    regex: 'Regex',
    profanity: 'Profanity',
    sexual: 'Sexual',
    violence: 'Violence',
    drugs: 'Drugs',
    gambling: 'Gambling',
    blasphemy: 'Blasphemy',
    discrimination: 'Discrimination',
    misogyny: 'Misogyny',
    humiliation: 'Humiliation',
    threat: 'Threat',
    other: 'Other',
    severity: 'Severity',
    severityFloor: 'Severity Floor',
    description: 'Description',
    exampleUsage: 'Example Usage',
    gcamArticleId: 'GCAM Article ID',
    gcamAtomId: 'GCAM Atom ID (optional)',
    gcamArticleTitle: 'GCAM Article Title',
    saveTerm: 'Save Term',
    // Settings
    myAccount: 'My Account',
    platformSettings: 'Platform Settings',
    security: 'Security',
    brandingReports: 'Branding & Reports',
    featureFlags: 'Feature Flags',
    profile: 'Profile',
    fullName: 'Full Name',
    preferredLanguage: 'Preferred Language',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    signOut: 'Sign Out',
    defaultLanguage: 'Default Language',
    defaultReportMode: 'Default Report Mode',
    inApp: 'In-App',
    standaloneHtml: 'Standalone HTML',
    both: 'Both',
    dateFormat: 'Date Format',
    versioningBehavior: 'Versioning Behavior',
    createVersionOnReplace: 'Create new version on file replace',
    requireOverrideReason: 'Require reason on overrides',
    sessionTimeout: 'Session Timeout (minutes)',
    forceRelogin: 'Force re-login on timeout',
    auditLogRetention: 'Audit Log Retention (days)',
    passwordPolicy: 'Password Policy',
    passwordPolicyDesc: 'Minimum 8 characters, upper/lowercase and numbers.',
    orgNameAr: 'Organization Name (Arabic)',
    orgNameEn: 'Organization Name (English)',
    logoUpload: 'Organization Logo (URL)',
    footerNoteAr: 'Footer Note (Arabic)',
    footerNoteEn: 'Footer Note (English)',
    showDecisionBadge: 'Show decision badge in printed report',
    paperSize: 'Default Paper Size',
    enableCertificates: 'Enable Certificates',
    enableLexiconCsv: 'Enable Lexicon CSV',
    enableHiddenOverrides: 'Enable Hidden-from-owner Overrides',
    saveChanges: 'Save Changes',
    settingsUpdated: 'Settings updated successfully',
    featureCertDesc: 'Enable Certificates management section in sidebar.',
    featureLexiconDesc: 'Allow importing and exporting lexicon terms via CSV.',
    featureHiddenDesc: 'Allow regulators to hide findings from script owners.'
  }
};

type Translations = typeof translations.en;

interface LangState {
  lang: Lang;
  toggleLang: () => void;
  t: (key: keyof Translations) => string;
}

export const useLangStore = create<LangState>((set, get) => ({
  lang: 'ar',
  toggleLang: () => set((state) => {
    const newLang = state.lang === 'ar' ? 'en' : 'ar';
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = newLang;
    return { lang: newLang };
  }),
  t: (key) => translations[get().lang][key] || key
}));