import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface PlatformSettings {
  defaultLanguage: 'ar' | 'en';
  reportMode: 'in_app' | 'standalone' | 'both';
  dateFormat: string;
  createVersionOnFileReplace: boolean;
  requireOverrideReason: boolean;
}

export interface SecuritySettings {
  sessionTimeoutMinutes: number;
  forceRelogin: boolean;
  auditLogRetentionDays: number;
}

export interface BrandingSettings {
  orgNameAr: string;
  orgNameEn: string;
  logoUrl: string;
  footerNoteAr: string;
  footerNoteEn: string;
  showDecisionBadgeInPrint: boolean;
}

export interface FeatureFlags {
  enableCertificates: boolean;
  enableLexiconCsv: boolean;
  enableHiddenOverrides: boolean;
}

export interface AppSettings {
  platform: PlatformSettings;
  security: SecuritySettings;
  branding: BrandingSettings;
  features: FeatureFlags;
}

interface SettingsState {
  settings: AppSettings;
  updateSettings: (newSettings: Partial<AppSettings>) => void;
}

const defaultSettings: AppSettings = {
  platform: {
    defaultLanguage: 'ar',
    reportMode: 'both',
    dateFormat: 'DD/MM/YYYY',
    createVersionOnFileReplace: true,
    requireOverrideReason: true,
  },
  security: {
    sessionTimeoutMinutes: 60,
    forceRelogin: false,
    auditLogRetentionDays: 90,
  },
  branding: {
    orgNameAr: 'راوي فيلم',
    orgNameEn: 'Raawi Film',
    logoUrl: '/dashboardlogo.png',
    footerNoteAr: 'هذا التقرير صادر عن منصة راوي فيلم للتحليل الآلي',
    footerNoteEn: 'This report is generated by Raawi Film Automated Analysis Platform',
    showDecisionBadgeInPrint: true,
  },
  features: {
    enableCertificates: false,
    enableLexiconCsv: true,
    enableHiddenOverrides: true,
  }
};

/** Minimum session timeout (minutes) — BUG-08: avoid sessions expiring after only a few minutes. */
const MIN_SESSION_TIMEOUT_MINUTES = 60;

export const useSettingsStore = create<SettingsState>()(
  persist(
    (set) => ({
      settings: defaultSettings,
      updateSettings: (newSettings) => set((state) => {
        const next = { ...state.settings, ...newSettings };
        if (next.security?.sessionTimeoutMinutes != null && next.security.sessionTimeoutMinutes < MIN_SESSION_TIMEOUT_MINUTES) {
          next.security = { ...next.security, sessionTimeoutMinutes: MIN_SESSION_TIMEOUT_MINUTES };
        }
        return { settings: next };
      }),
    }),
    {
      name: 'raawi-settings',
      partialize: (state) => ({ settings: state.settings }),
      onRehydrateStorage: () => (state) => {
        if (!state?.settings?.security) return;
        if (state.settings.security.sessionTimeoutMinutes < MIN_SESSION_TIMEOUT_MINUTES) {
          state.settings.security.sessionTimeoutMinutes = MIN_SESSION_TIMEOUT_MINUTES;
        }
      },
    }
  )
);
