export const DRUGS_RULES = Object.freeze({
  drugAnchors: Object.freeze([
    "drug",
    "drugs",
    "substance",
    "narcotic",
    "narcotics",
    "drug use",
    "drug consumption",
    "drug possession",
    "drug distribution",
    "drug sale",
    "drug purchase",
    "drug smuggling",
    "drug trafficking",
    "drug manufacturing",
    "drug cultivation",
    "drug storage",
    "drug transportation",
    "drug glorification",
    "drug encouragement",
    "drug instruction",
    "drug normalization",
    "drug dependency",
    "drug addiction",
    "drug overdose",
    "drug rehabilitation",
    "medical drug use",
    "prescription drug use",
    "illegal prescription use",
    "drug documentary",
    "drug educational",
    "drug historical",
    "drug news",
    "drug comedy",
    "drug satire",
    "drug dream",
    "drug flashback",
    "drug hallucination",
    "drug false accusation",
    "drug symbolism",
    "drug implied use",
    "مخدر",
    "مخدرات",
    "حبوب",
    "حشيش",
    "كوكايين",
    "هيروين",
    "ترامادول",
    "دواء",
    "علاج",
  ]),
  directTerms: Object.freeze([
    "drug_consumption",
    "drug_possession",
    "drug_distribution",
    "drug_sale",
    "drug_purchase",
    "drug_smuggling",
    "drug_trafficking",
    "drug_manufacturing",
    "drug_cultivation",
    "drug_storage",
    "drug_transportation",
    "drug_glorification",
    "drug_encouragement",
    "drug_instruction",
    "drug_normalization",
    "drug_dependency",
    "drug_addiction",
    "drug_overdose",
    "medical_drug_use",
    "prescription_drug_use",
    "illegal_prescription_use",
    "drug_dialogue",
    "drug_scene_description",
    "drug_reference",
    "drug_implied_use",
    "drug use",
    "consumption",
    "possession",
    "sale",
    "distribution",
    "trafficking",
    "manufacturing",
    "cultivation",
    "storage",
    "transportation",
    "overdose",
    "dependency",
    "addiction",
    "rehabilitation",
    "promotion",
    "glorification",
    "encouragement",
    "instruction",
    "المخدر",
    "المخدرات",
    "يتعاطى",
    "يتناول الحبة",
    "يأخذ الحبة",
    "يشتري المخدر",
    "يبيع المخدر",
    "يخزن المخدر",
    "يهرّب المخدر",
    "يصنع المخدر",
    "يتاجر بالمخدر",
    "جرعة زائدة",
  ]),
  manufacturingTerms: Object.freeze([
    "drug_manufacturing",
    "manufacturing",
    "يصنع",
    "إنتاج",
    "مختبر",
    "factory",
  ]),
  traffickingTerms: Object.freeze([
    "drug_trafficking",
    "trafficking",
    "smuggling",
    "يهرّب",
    "تهريب",
    "نقل المخدر",
    "توزيع المخدر",
    "يخفيها",
  ]),
  useTerms: Object.freeze([
    "drug_consumption",
    "drug use",
    "consumption",
    "يتعاطى",
    "يتناول",
    "يأخذ الحبة",
    "يدخنها",
  ]),
  promotionTerms: Object.freeze([
    "drug_glorification",
    "drug_encouragement",
    "drug_normalization",
    "promotion",
    "glorification",
    "encouragement",
    "جربها",
    "ستحبها",
    "عادي",
    "لا بأس",
    "فخر",
  ]),
  educationalSignals: Object.freeze([
    "drug educational",
    "educational",
    "education",
    "instruction",
    "teaching",
    "lesson",
    "شرح",
    "تعليمي",
    "درس",
    "تثقيف",
    "تحذير",
  ]),
  medicalSignals: Object.freeze([
    "medical drug use",
    "prescription drug use",
    "medical",
    "clinic",
    "doctor",
    "patient",
    "dose",
    "dosage",
    "treatment",
    "rehabilitation",
    "علاج",
    "طبي",
    "دواء",
    "وصفة",
    "جرعة",
    "عيادة",
  ]),
  rehabilitationSignals: Object.freeze([
    "drug rehabilitation",
    "rehabilitation",
    "recovery",
    "sober",
    "support group",
    "مركز تأهيل",
    "تعاف",
    "علاج الإدمان",
  ]),
  quotationSignals: Object.freeze([
    "\"",
    "«",
    "»",
    "quoted",
    "quote",
    "quotation",
    "اقتباس",
    "منقول",
  ]),
  condemnationSignals: Object.freeze([
    "condemn",
    "condemnation",
    "أدين",
    "أرفض",
    "مرفوض",
    "wrong",
    "خاطئ",
    "dangerous",
  ]),
  documentarySignals: Object.freeze([
    "documentary",
    "وثائقي",
    "تسجيلي",
    "reportage",
    "archive",
  ]),
  historicalSignals: Object.freeze([
    "historical",
    "history",
    "تاريخي",
    "تاريخ",
  ]),
  newsSignals: Object.freeze([
    "news",
    "خبر",
    "reported",
    "report",
  ]),
  courtSignals: Object.freeze([
    "court",
    "trial",
    "testimony",
    "محكمة",
    "شهادة",
  ]),
  fictionSignals: Object.freeze([
    "fiction",
    "story",
    "film",
    "movie",
    "novel",
    "رواية",
    "فيلم",
    "مسلسل",
  ]),
  comedySignals: Object.freeze([
    "comedy",
    "comic",
    "ساخر",
    "كوميديا",
  ]),
  satireSignals: Object.freeze([
    "satire",
    "satirical",
    "ساخر",
    "سخرية",
  ]),
  dreamSignals: Object.freeze([
    "dream",
    "حلم",
    "منام",
  ]),
  flashbackSignals: Object.freeze([
    "flashback",
    "استرجاع",
    "فلاش باك",
  ]),
  hallucinationSignals: Object.freeze([
    "hallucination",
    "hallucinating",
    "هذيان",
    "وهم",
  ]),
  falseAccusationSignals: Object.freeze([
    "false accusation",
    "اتهام كاذب",
    "افتراء",
    "ليس مخدرًا",
  ]),
  sceneSignals: Object.freeze([
    "scene",
    "dialogue",
    "description",
    "sound",
    "camera",
  ]),
});
