export const VIOLENCE_RULES = Object.freeze({
  violenceAnchors: Object.freeze([
    "violence",
    "violent",
    "violence event",
    "graphic violence",
    "domestic violence",
    "self-defense",
    "self defense",
    "justified violence",
    "condemned violence",
    "documentary violence",
    "weapon",
    "weapons",
    "knife",
    "gun",
    "pistol",
    "rifle",
    "blade",
    "assault",
    "attack",
    "murder",
    "kill",
    "torture",
    "beating",
    "blood",
    "gore",
    "عنف",
    "عنيف",
    "عنف منزلي",
    "دفاع عن النفس",
    "مبرر",
    "مشهد دموي",
    "عنف وثائقي",
    "سلاح",
    "سكاكين",
    "مسدس",
    "بندقية",
    "قتل",
    "ذبح",
    "طعن",
    "ضرب",
    "اعتداء",
    "تعذيب",
  ]),
  directViolenceTerms: Object.freeze([
    "violence_event",
    "violence_threat",
    "violence_attempt",
    "violence_glorification",
    "violence_encouragement",
    "violence_instruction",
    "violence_reward",
    "violence_revenge",
    "graphic violence",
    "domestic violence",
    "murder",
    "torture",
    "kill",
    "قتل",
    "طعن",
    "ضرب",
    "اعتداء",
    "تعذيب",
    "هجوم",
  ]),
  weaponTerms: Object.freeze([
    "weapon",
    "weapons",
    "knife",
    "gun",
    "pistol",
    "rifle",
    "blade",
    "sword",
    "bomb",
    "explosive",
    "سلاح",
    "سكاكين",
    "مسدس",
    "بندقية",
    "سكين",
    "قنبلة",
    "متفجرات",
  ]),
  selfDefenseTerms: Object.freeze([
    "violence_self_defense",
    "self-defense",
    "self defense",
    "دافع عن نفسه",
    "دافعت عن نفسها",
    "دفاع عن النفس",
    "رد الاعتداء",
    "لحماية نفسه",
  ]),
  lawEnforcementTerms: Object.freeze([
    "violence_law_enforcement",
    "law enforcement",
    "police use of force",
    "استخدام القوة",
    "الشرطة",
    "ضبط",
    "اعتقال",
  ]),
  justifiedTerms: Object.freeze([
    "justified violence",
    "justified",
    "مبرر",
    "مبرر للعنف",
    "دفاع مشروع",
    "ضرورة",
  ]),
  condemnationTerms: Object.freeze([
    "violence_condemnation",
    "condemn",
    "condemnation",
    "أدين العنف",
    "أدين",
    "أرفض",
    "أرفض العنف",
    "العنف مرفوض",
    "العنف خطأ",
    "مدان",
    "wrong violence",
  ]),
  documentaryTerms: Object.freeze([
    "violence_documentary",
    "documentary violence",
    "documentary",
    "وثائقي",
    "تسجيلي",
    "archival",
    "archive footage",
    "reportage",
  ]),
  fictionTerms: Object.freeze([
    "violence_fantasy",
    "fiction",
    "story",
    "novel",
    "film",
    "movie",
    "رواية",
    "قصة",
    "فيلم",
    "مسلسل",
  ]),
  rolePlayTerms: Object.freeze([
    "roleplay",
    "role play",
    "acting",
    "stage play",
    "مسرحية",
    "تمثيل",
  ]),
  historicalTerms: Object.freeze([
    "violence_historical",
    "historical violence",
    "historical",
    "تاريخي",
  ]),
  trainingTerms: Object.freeze([
    "violence_training",
    "training",
    "instruction",
    "درس",
    "تدريب",
    "تعليمي",
  ]),
  gameTerms: Object.freeze([
    "violence_game",
    "game",
    "video game",
    "لعبة",
  ]),
  fantasyTerms: Object.freeze([
    "violence_fantasy",
    "fantasy",
    "خيال",
  ]),
  comedyTerms: Object.freeze([
    "violence_comedy",
    "comedy",
    "comedic",
    "كوميديا",
    "ساخر",
    "سخرية",
  ]),
  dreamTerms: Object.freeze([
    "violence_dream",
    "dream",
    "حلم",
  ]),
  flashbackTerms: Object.freeze([
    "violence_flashback",
    "flashback",
    "استرجاع",
    "فلاش باك",
  ]),
  memoryTerms: Object.freeze([
    "violence_memory",
    "memory",
    "ذكري",
    "ذكرى",
  ]),
  imaginationTerms: Object.freeze([
    "violence_imagination",
    "imagination",
    "imagined",
    "متخيل",
  ]),
  failedAttemptTerms: Object.freeze([
    "violence_failed_attempt",
    "failed attempt",
    "failed to kill",
    "failed to attack",
    "فشل في",
    "حاول ولم ينجح",
  ]),
  offscreenTerms: Object.freeze([
    "violence_offscreen",
    "off-screen",
    "offscreen",
    "خارج الكادر",
    "خلف الكاميرا",
  ]),
  sceneDescriptionTerms: Object.freeze([
    "violence_scene_description",
    "scene description",
    "وصف المشهد",
  ]),
  dialogueTerms: Object.freeze([
    "violence_dialogue",
    "dialogue",
    "حوار",
  ]),
  reportedByCharacterTerms: Object.freeze([
    "violence_reported_by_character",
    "reported by",
    "روى",
    "قال إن",
  ]),
  observedTerms: Object.freeze([
    "violence_observed",
    "observed",
    "شاهد",
    "رأى",
  ]),
  impliedTerms: Object.freeze([
    "violence_implied",
    "implied",
    "ضمني",
    "موحي",
  ]),
  againstChildTerms: Object.freeze([
    "violence_against_child",
    "against child",
    "child abuse",
    "child violence",
    "طفل",
    "قاصر",
    "الطفل",
  ]),
  againstWomanTerms: Object.freeze([
    "violence_against_woman",
    "against woman",
    "woman",
    "امرأة",
    "المرأة",
  ]),
  againstDisabledTerms: Object.freeze([
    "violence_against_disabled",
    "against disabled",
    "disabled",
    "معاق",
    "ذوي الإعاقة",
    "ذوي الاعاقة",
  ]),
  againstPublicTerms: Object.freeze([
    "violence_against_public",
    "against public",
    "public",
    "الناس",
    "الجمهور",
  ]),
  againstStateTerms: Object.freeze([
    "violence_against_state",
    "against state",
    "state",
    "الدولة",
    "الحكومة",
  ]),
});
