export type ProfanityRuleSet = {
  readonly directTerms: readonly string[];
  readonly directPhrases: readonly string[];
  readonly condemnationSignals: readonly string[];
  readonly educationalSignals: readonly string[];
  readonly quotationSignals: readonly string[];
};

export const PROFANITY_RULES: ProfanityRuleSet = {
  directTerms: [
    "يلعن",
    "العن",
    "لعن",
    "لعنة",
    "لعنك",
    "تبا",
    "تبًا",
    "تباً",
    "خرا",
    "وسخ",
    "قذر",
    "حقير",
    "وضيع",
    "نذل",
    "خسيس",
    "لئيم",
    "جبان",
    "ساقط",
    "غبي",
    "أحمق",
    "سخيف",
    "كلب",
    "حمار",
    "أهبل",
    "اهبل",
    "كذاب",
    "حرامي",
    "نصاب",
    "نابي",
    "نابية",
    "شتيمة",
    "سباب",
    "قذف",
  ],
  directPhrases: [
    "يا حمار",
    "يا كلب",
    "يا خرا",
    "كس امة",
    "كس أمة",
    "العن امك",
    "العن أمك",
    "العن والديك",
    "يا كذاب",
    "يا نصاب",
    "يا حرامي",
    "عديم التربية",
    "ما تسوى شيء",
    "لا أحد يبيك",
  ],
  condemnationSignals: [
    "يستنكر",
    "ينتقد",
    "يدين",
    "إدانة",
    "يُدين",
    "رفض",
    "يرفض",
    "مرفوض",
    "لا يجوز",
    "مذموم",
    "مستنكر",
    "سيء",
    "غير لائق",
  ],
  educationalSignals: [
    "تعليمي",
    "تعليم",
    "شرح",
    "يشرح",
    "مثال",
    "أمثلة",
    "درس",
    "توضيح",
    "توضيحًا",
    "يناقش",
    "مناقشة",
    "تحليل",
  ],
  quotationSignals: [
    "اقتباس",
    "اقتبس",
    "quoted",
    "quote",
    "نصًا",
    "حرفيًا",
    "«",
    "»",
    "\"",
  ],
};
