export const CHILDREN_RULES = Object.freeze({
  childAnchors: Object.freeze([
    "child",
    "children",
    "طفل",
    "طفلة",
    "قاصر",
    "minor",
    "infant",
    "teenager",
    "kid",
    "baby",
    "vulnerable person",
    "vulnerable_person",
    "disabled child",
    "disabled_child",
    "disabled adult",
    "disabled_adult",
    "elderly person",
    "elderly_person",
  ]),
  abuseTerms: Object.freeze([
    "abuse",
    "physical abuse",
    "child abuse",
    "إساءة",
    "اعتداء",
    "يضرب الطفل",
    "يضرب القاصر",
    "beat the child",
    "hit the child",
    "beat the minor",
    "hit the minor",
  ]),
  neglectTerms: Object.freeze([
    "neglect",
    "child neglect",
    "إهمال",
    "ترك الطفل",
    "ترك القاصر",
    "abandonment",
    "abandon the child",
    "leave the child alone",
    "leave the minor alone",
  ]),
  exploitationTerms: Object.freeze([
    "exploitation",
    "child exploitation",
    "استغلال",
    "استغل الطفل",
    "استغلال الطفل",
    "forced labor",
    "work the child",
    "use the child",
    "traffic the child",
    "trafficking",
  ]),
  groomingTerms: Object.freeze([
    "grooming",
    "child grooming",
    "تغرير",
    "استدراج الطفل",
    "استدرج الطفل",
    "seduce the child",
    "lure the child",
    "secret gifts",
  ]),
  violenceTerms: Object.freeze([
    "violence against child",
    "child violence",
    "assault the child",
    "attack the child",
    "تهديد الطفل",
    "يهدد الطفل",
    "يهدد",
    "تهديد",
    "يهدده",
    "تهدد",
    "threaten the child",
    "kill the child",
    "قتل الطفل",
    "beat the child",
  ]),
  crimeTerms: Object.freeze([
    "child crime",
    "criminal exploitation",
    "أجبر الطفل على السرقة",
    "forced the child to steal",
    "forced the child to smuggle",
    "used the child to commit crime",
    "used the minor to commit crime",
    "gang",
    "smuggle",
    "steal",
    "robbery",
  ]),
  psychologicalAbuseTerms: Object.freeze([
    "psychological abuse",
    "bullying",
    "humiliation",
    "fear induction",
    "isolation",
    "mocking disability",
    "disability abuse",
    "insult the child",
    "threaten the child",
    "terrorize the child",
    "يسخرون",
    "يسخر من الطفل",
    "يذلونه",
    "إذلال",
    "إهانة",
    "تنمر",
    "يخيف الطفل",
    "خوف الطفل",
    "يرهب الطفل",
  ]),
  quotationSignals: Object.freeze([
    "quoted",
    "quote",
    "quotation",
    "قال:",
    "يقول:",
    "\"",
    "«",
  ]),
  educationalSignals: Object.freeze([
    "educational",
    "education",
    "instruction",
    "lesson",
    "teach",
    "tutorial",
    "lecture",
    "شرح",
    "درس",
    "تعليمي",
    "نشرح",
  ]),
  documentarySignals: Object.freeze([
    "documentary",
    "وثائقي",
    "reportage",
    "archive",
  ]),
  historicalSignals: Object.freeze([
    "historical",
    "historical narration",
    "historical account",
    "تاريخي",
  ]),
  newsSignals: Object.freeze([
    "news",
    "خبر",
    "reported",
    "report",
  ]),
  courtSignals: Object.freeze([
    "court",
    "trial",
    "testimony",
    "محكمة",
    "شهادة",
  ]),
  condemnationSignals: Object.freeze([
    "condemn",
    "condemnation",
    "refuse",
    "reject",
    "مرفوض",
    "أدين",
    "reject this",
    "wrong",
  ]),
  fictionSignals: Object.freeze([
    "fiction",
    "story",
    "novel",
    "film",
    "movie",
    "رواية",
    "قصة",
    "فيلم",
    "مسلسل",
  ]),
  rolePlaySignals: Object.freeze([
    "roleplay",
    "role play",
    "acting",
    "stage play",
    "مسرحية",
    "تمثيل",
  ]),
  dreamSignals: Object.freeze([
    "dream",
    "حلم",
  ]),
  flashbackSignals: Object.freeze([
    "flashback",
    "استرجاع",
    "فلاش باك",
  ]),
  satireSignals: Object.freeze([
    "satire",
    "سخرية",
    "تهكم",
  ]),
});
