export const SEXUALITY_RULES = Object.freeze({
  sexualityAnchors: Object.freeze([
    "sexuality",
    "sexual content",
    "sexual",
    "sex scene",
    "explicit scene",
    "implied scene",
    "nudity",
    "nude",
    "naked",
    "topless",
    "revealing",
    "intimate",
    "intimacy",
    "romance",
    "flirting",
    "kiss",
    "touch",
    "erotic",
    "sensual",
    "suggestive",
    "innuendo",
    "double meaning",
    "metaphor",
    "symbolism",
    "sexual reference",
    "sexual dialogue",
    "sexual scene",
    "sexual description",
    "sexual clothing",
    "sexual camera focus",
    "sexual body focus",
    "sexual sound",
    "sexual joke",
    "sexual invitation",
    "sexual suggestion",
    "sexual harassment",
    "sexual exploitation",
    "sexual grooming",
    "إيحاء",
    "تلميح",
    "عري",
    "عارية",
    "عاري",
    "مشهد حميم",
    "مشهد صريح",
    "مشهد جنسي",
    "غزل",
    "قبلات",
  ]),
  directTerms: Object.freeze([
    "sexual_reference",
    "sexual_joke",
    "sexual_double_meaning",
    "sexual_metaphor",
    "sexual_symbolism",
    "sexual_flirting",
    "sexual_romance",
    "sexual_suggestion",
    "sexual_invitation",
    "sexual_kiss",
    "sexual_intimacy",
    "sexual_touch",
    "sexual_dancing",
    "sexual_dialogue",
    "sexual_scene",
    "sexual_description",
    "sexual_sound",
    "sexual_camera_focus",
    "sexual_body_focus",
    "sexual_clothing",
    "sexual_normalization",
    "sexual_glorification",
    "sexual_instruction",
    "sexual_comedy",
    "sexual_condemnation",
    "sexual_documentary",
    "sexual_medical",
    "sexual_educational",
    "sexual_historical",
    "nudity",
    "explicit scene",
    "explicit scenes",
    "sex scene",
    "nude",
    "naked",
    "topless",
    "bare body",
    "sexualized body",
    "breasts",
    "genitals",
    "kiss",
    "touch",
    "flirting",
    "romance",
    "غزل",
    "قبلات",
    "عري",
    "مشهد صريح",
    "مشهد جنسي",
  ]),
  impliedTerms: Object.freeze([
    "implied scene",
    "implied sexual",
    "sexual suggestion",
    "sexual invitation",
    "sexual double meaning",
    "innuendo",
    "subtext",
    "hint",
    "suggestive",
    "implicit",
    "موحى",
    "إيحاء",
    "تلميح",
  ]),
  explicitTerms: Object.freeze([
    "explicit",
    "graphic",
    "nudity",
    "nude",
    "naked",
    "topless",
    "bare",
    "breasts",
    "genitals",
    "sex scene",
    "scene of nudity",
    "مشهد صريح",
    "عري",
    "مشهد عار",
  ]),
  nudityTerms: Object.freeze([
    "nudity",
    "nude",
    "naked",
    "topless",
    "bare",
    "عري",
    "عارية",
    "عار",
  ]),
  bodyFocusTerms: Object.freeze([
    "body focus",
    "sexual body focus",
    "camera focus",
    "camera linger",
    "lingering shot",
    "close-up",
    "visual framing",
    "framing",
    "كشف الجسد",
  ]),
  clothingTerms: Object.freeze([
    "sexual clothing",
    "revealing",
    "lingerie",
    "underwear",
    "swimwear",
    "شفاف",
    "مكشوف",
    "ملابس مثيرة",
  ]),
  soundTerms: Object.freeze([
    "sexual sound",
    "moan",
    "moaning",
    "whisper",
    "breathless",
    "أنين",
    "همس",
  ]),
  educationalSignals: Object.freeze([
    "educational",
    "education",
    "instruction",
    "teaching",
    "teaching about sex",
    "biology lesson",
    "sex education",
    "شرح",
    "تعليمي",
    "درس",
    "تثقيف",
  ]),
  medicalSignals: Object.freeze([
    "medical",
    "clinic",
    "doctor",
    "exam",
    "examination",
    "health",
    "gynecology",
    "obstetrics",
    "sexual health",
    "فحص طبي",
    "طبي",
    "عيادة",
    "تشخيص",
  ]),
  artisticSignals: Object.freeze([
    "artistic",
    "art",
    "aesthetic",
    "cinematic",
    "cinematography",
    "framing",
    "visual composition",
    "mise-en-scène",
    "director's cut",
    "فنّي",
    "فني",
    "جمالي",
  ]),
  quotationSignals: Object.freeze([
    "\"",
    "«",
    "»",
    "quoted",
    "quote",
    "quotation",
    "اقتباس",
    "منقول",
  ]),
  condemnationSignals: Object.freeze([
    "condemn",
    "condemnation",
    "أدين",
    "أرفض",
    "مرفوض",
    "wrong",
    "haram",
  ]),
  historicalSignals: Object.freeze([
    "historical",
    "history",
    "historical narration",
    "تاريخي",
    "تاريخ",
  ]),
  documentarySignals: Object.freeze([
    "documentary",
    "وثائقي",
    "تسجيلي",
    "reportage",
    "archive",
  ]),
  newsSignals: Object.freeze([
    "news",
    "خبر",
    "reported",
    "report",
  ]),
  courtSignals: Object.freeze([
    "court",
    "trial",
    "testimony",
    "محكمة",
    "شهادة",
  ]),
  fictionSignals: Object.freeze([
    "fiction",
    "story",
    "film",
    "movie",
    "novel",
    "رواية",
    "فيلم",
    "مسلسل",
  ]),
  rolePlaySignals: Object.freeze([
    "roleplay",
    "role play",
    "acting",
    "تمثيل",
    "مسرحية",
  ]),
  dreamSignals: Object.freeze([
    "dream",
    "حلم",
    "منام",
  ]),
  flashbackSignals: Object.freeze([
    "flashback",
    "استرجاع",
    "فلاش باك",
  ]),
  imaginationSignals: Object.freeze([
    "imagination",
    "imagined",
    "متخيل",
  ]),
  childSignals: Object.freeze([
    "child",
    "children",
    "minor",
    "underage",
    "grooming",
    "طفل",
    "قاصر",
    "بنت صغيرة",
    "ولد صغير",
  ]),
  harassmentSignals: Object.freeze([
    "sexual_harassment",
    "harassment",
    "تحرش",
  ]),
  exploitationSignals: Object.freeze([
    "sexual_exploitation",
    "exploitation",
    "استغلال",
  ]),
  groomingSignals: Object.freeze([
    "sexual_grooming",
    "grooming",
    "استدراج",
    "تغرير",
  ]),
  falseAccusationSignals: Object.freeze([
    "sexual_false_accusation",
    "false accusation",
    "false accusation",
    "اتهام كاذب",
    "افتراء",
  ]),
  sceneSignals: Object.freeze([
    "scene",
    "dialogue",
    "description",
    "sound",
    "camera",
    "body language",
    "scene description",
  ]),
});
