import { Font, StyleSheet } from '@react-pdf/renderer';

const fontBase = typeof window !== 'undefined' ? window.location.origin : '';

Font.register({
  family: 'ReportBuilderCairo',
  fonts: [
    { src: `${fontBase}/fonts/Cairo-Regular.ttf` },
    { src: `${fontBase}/fonts/Cairo-Bold.ttf`, fontWeight: 'bold' },
  ],
});

export const builderPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingHorizontal: 32,
    paddingBottom: 32,
    fontFamily: 'ReportBuilderCairo',
    fontSize: 9.5,
    color: '#1f1630',
    backgroundColor: '#ffffff',
  },
  rtl: {
    direction: 'rtl',
    textAlign: 'right',
  },
  cover: {
    padding: 0,
    backgroundColor: '#f7f4f8',
    fontFamily: 'ReportBuilderCairo',
  },
  coverFrame: {
    position: 'relative',
    width: '100%',
    height: '100%',
    padding: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  coverInner: {
    width: '100%',
    maxWidth: 430,
    alignItems: 'center',
    textAlign: 'center',
  },
  coverBadge: {
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#eaddea',
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  coverBadgeText: {
    fontSize: 8.5,
    color: '#7a2f63',
    fontWeight: 700,
    letterSpacing: 0.6,
  },
  coverRule: {
    width: 72,
    height: 2,
    backgroundColor: '#7a2f63',
    borderRadius: 99,
    marginTop: 12,
    marginBottom: 16,
  },
  coverPanel: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e4d7e1',
    borderRadius: 16,
    backgroundColor: '#fff',
    padding: 14,
    marginTop: 16,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  coverPanelTitle: {
    fontSize: 9,
    fontWeight: 700,
    color: '#665a73',
    marginBottom: 10,
  },
  coverGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  coverStat: {
    width: '49%',
    borderWidth: 1,
    borderColor: '#f0e7ee',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: '#fcfbfd',
  },
  coverStatLabel: {
    fontSize: 7.8,
    color: '#7e6f88',
    marginBottom: 3,
  },
  coverStatValue: {
    fontSize: 10.5,
    fontWeight: 700,
    color: '#1f1630',
  },
  coverNote: {
    fontSize: 8.5,
    lineHeight: 1.4,
    color: '#6a5f76',
    marginTop: 14,
  },
  brand: {
    fontSize: 11,
    color: '#7a2f63',
    marginBottom: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 8,
    color: '#1f1630',
  },
  subtitle: {
    fontSize: 11.5,
    lineHeight: 1.4,
    color: '#5d5470',
    marginBottom: 14,
    maxWidth: 440,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    marginTop: 12,
  },
  metaChip: {
    borderWidth: 1,
    borderColor: '#e4d7e1',
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    minWidth: 110,
  },
  metaLabel: {
    fontSize: 8,
    color: '#7e6f88',
    marginBottom: 2,
  },
  metaValue: {
    fontSize: 10,
    fontWeight: 700,
    color: '#1f1630',
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 8,
    marginTop: 12,
    color: '#1f1630',
  },
  headerTag: {
    fontSize: 8.5,
    color: '#7a2f63',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
    fontWeight: 700,
  },
  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eaddea',
  },
  overviewLayout: {
    flexDirection: 'row',
    gap: 12,
  },
  overviewLeft: {
    flex: 1.45,
  },
  overviewRight: {
    flex: 0.85,
  },
  panel: {
    borderWidth: 1,
    borderColor: '#e6dce4',
    borderRadius: 10,
    backgroundColor: '#fcfbfd',
    padding: 10,
  },
  panelTitle: {
    fontSize: 9.5,
    fontWeight: 700,
    color: '#1f1630',
    marginBottom: 8,
  },
  panelSubtle: {
    fontSize: 8,
    color: '#7b7385',
    marginTop: 4,
  },
  kvRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#f0e7ee',
  },
  kvLabel: {
    flex: 0.9,
    fontSize: 8.5,
    color: '#665a73',
    paddingRight: 6,
  },
  kvValue: {
    flex: 1.1,
    fontSize: 8.5,
    fontWeight: 700,
    color: '#1f1630',
    textAlign: 'right',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -3,
    marginTop: 4,
  },
  chip: {
    borderWidth: 1,
    borderColor: '#e4d7e1',
    backgroundColor: '#fff',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 8,
    margin: 3,
  },
  chipText: {
    fontSize: 7.8,
    color: '#4c3a57',
  },
  sectionNote: {
    fontSize: 9,
    color: '#6a5f76',
    marginBottom: 12,
  },
  cardsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  statCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#eaddea',
    borderRadius: 10,
    padding: 10,
    backgroundColor: '#fcfbfd',
  },
  statValue: {
    fontSize: 16,
    fontWeight: 700,
    color: '#7a2f63',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 8.5,
    color: '#665a73',
  },
  table: {
    borderWidth: 1,
    borderColor: '#e6dce4',
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 8,
  },
  tr: {
    flexDirection: 'row',
  },
  th: {
    flex: 1,
    paddingVertical: 7,
    paddingHorizontal: 6,
    fontSize: 8,
    fontWeight: 700,
    backgroundColor: '#f8f4f7',
    borderRightWidth: 1,
    borderRightColor: '#eaddea',
    color: '#392b45',
  },
  td: {
    flex: 1,
    paddingVertical: 7,
    paddingHorizontal: 6,
    fontSize: 8,
    borderRightWidth: 1,
    borderRightColor: '#f0e7ee',
    color: '#2c2140',
  },
  tableHeaderBand: {
    backgroundColor: '#f8f4f7',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eaddea',
  },
  tableHeaderMeta: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 6,
  },
  statPill: {
    borderWidth: 1,
    borderColor: '#e4d7e1',
    backgroundColor: '#fff',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  statPillText: {
    fontSize: 7.8,
    color: '#4c3a57',
  },
  muted: {
    color: '#7b7385',
  },
  footer: {
    marginTop: 10,
    fontSize: 8,
    color: '#7b7385',
  },
});
