export const CRIME_RULES = Object.freeze({
  crimeAnchors: Object.freeze([
    "crime",
    "criminal",
    "robbery",
    "burglary",
    "fraud",
    "forgery",
    "blackmail",
    "extortion",
    "bribery",
    "corruption",
    "money laundering",
    "kidnapping",
    "hostage",
    "murder",
    "assault",
    "arson",
    "vandalism",
    "smuggling",
    "organized crime",
    "cybercrime",
    "identity theft",
    "theft",
    "steal",
    "thief",
    "سرقة",
    "سطو",
    "اختطاف",
    "ابتزاز",
    "رشوة",
    "فساد",
    "غسل الأموال",
    "تهريب",
    "جريمة",
    "مجرم",
    "قتل",
    "اعتداء",
    "سرق",
    "يسرق",
    "سنسرق",
  ]),
  directTerms: Object.freeze([
    "crime_reference",
    "crime_attempt",
    "crime_conspiracy",
    "crime_planning",
    "crime_execution",
    "crime_glorification",
    "crime_encouragement",
    "crime_instruction",
    "crime_normalization",
    "crime_reward",
    "crime_coverup",
    "crime_escape",
    "crime_evasion",
    "crime_theft",
    "crime_robbery",
    "crime_burglary",
    "crime_fraud",
    "crime_forgery",
    "crime_blackmail",
    "crime_extortion",
    "crime_bribery",
    "crime_corruption",
    "crime_money_laundering",
    "crime_kidnapping",
    "crime_hostage",
    "crime_murder",
    "crime_attempted_murder",
    "crime_assault",
    "crime_property_damage",
    "crime_vandalism",
    "crime_arson",
    "crime_human_trafficking",
    "crime_smuggling",
    "crime_organized_crime",
    "crime_cybercrime",
    "crime_identity_theft",
    "crime_documentary",
    "crime_news",
    "crime_historical",
    "crime_educational",
    "crime_police_investigation",
    "crime_court_case",
    "crime_false_accusation",
    "crime_confession",
    "crime_scene_description",
    "crime_dialogue",
    "crime_observation",
    "crime_reported_event",
  ]),
  violentTerms: Object.freeze([
    "crime_murder",
    "crime_attempted_murder",
    "crime_assault",
    "crime_kidnapping",
    "crime_hostage",
    "crime_human_trafficking",
    "murder",
    "attempted murder",
    "assault",
    "kidnapping",
    "hostage",
    "human trafficking",
    "قتل",
    "اعتداء",
    "اختطاف",
    "رهينة",
  ]),
  propertyTerms: Object.freeze([
    "crime_theft",
    "crime_robbery",
    "crime_burglary",
    "crime_property_damage",
    "crime_vandalism",
    "crime_arson",
    "theft",
    "robbery",
    "burglary",
    "property damage",
    "vandalism",
    "arson",
    "سرقة",
    "سرق",
    "سطو",
    "تخريب",
    "حرق",
  ]),
  financialTerms: Object.freeze([
    "crime_fraud",
    "crime_forgery",
    "crime_blackmail",
    "crime_extortion",
    "crime_bribery",
    "crime_corruption",
    "crime_money_laundering",
    "crime_identity_theft",
    "crime_cybercrime",
    "fraud",
    "forgery",
    "blackmail",
    "extortion",
    "bribery",
    "corruption",
    "money laundering",
    "identity theft",
    "cybercrime",
    "احتيال",
    "تزوير",
    "ابتزاز",
    "رشوة",
    "فساد",
    "غسل الأموال",
  ]),
  organizedTerms: Object.freeze([
    "crime_reference",
    "crime_attempt",
    "crime_conspiracy",
    "crime_planning",
    "crime_execution",
    "crime_coverup",
    "crime_escape",
    "crime_evasion",
    "crime_smuggling",
    "crime_organized_crime",
    "organized crime",
    "conspiracy",
    "planning",
    "execution",
    "coverup",
    "escape",
    "evasion",
    "smuggling",
    "تهريب",
    "تواطؤ",
    "خطة",
    "هروب",
  ]),
  quotationSignals: Object.freeze(["quoted", "quote", "quotation", "«", "»", "\"", "اقتباس"]),
  educationalSignals: Object.freeze(["educational", "education", "instruction", "lesson", "شرح", "تعليمي", "درس"]),
  documentarySignals: Object.freeze(["documentary", "وثائقي", "تسجيلي", "archive"]),
  historicalSignals: Object.freeze(["historical", "history", "تاريخي", "تاريخ"]),
  newsSignals: Object.freeze(["news", "خبر", "reported", "report"]),
  courtSignals: Object.freeze(["court", "trial", "testimony", "محكمة", "شهادة"]),
  policeSignals: Object.freeze(["police", "investigation", "شرطة", "تحقيق"]),
  condemnationSignals: Object.freeze(["condemn", "condemnation", "أدين", "أرفض", "مرفوض", "wrong", "خطأ"]),
  fictionSignals: Object.freeze(["fiction", "story", "film", "movie", "novel", "رواية", "فيلم", "مسلسل"]),
  satireSignals: Object.freeze(["satire", "satirical", "ساخر", "سخرية", "تهكم"]),
  comedySignals: Object.freeze(["comedy", "comic", "كوميديا"]),
  dreamSignals: Object.freeze(["dream", "حلم", "منام"]),
  flashbackSignals: Object.freeze(["flashback", "استرجاع", "فلاش باك"]),
  rolePlaySignals: Object.freeze(["roleplay", "role play", "acting", "تمثيل", "مسرحية"]),
  neutralReportSignals: Object.freeze(["reported event", "report", "observation", "description", "observed"]),
});
