export const POLITICS_RULES = Object.freeze({
  politicsAnchors: Object.freeze([
    "politics",
    "political",
    "state",
    "government",
    "governance",
    "head of state",
    "royal family",
    "constitutional",
    "national flag",
    "national anthem",
    "national symbol",
    "national identity",
    "national unity",
    "patriotism",
    "foreign government",
    "foreign leader",
    "international organization",
    "diplomatic",
    "election",
    "voting",
    "revolution",
    "coup",
    "public demonstration",
    "civil unrest",
    "riot",
    "rally",
    "state security",
    "national security",
    "police",
    "military",
    "intelligence",
    "دولة",
    "حكومة",
    "سياسة",
    "سياسي",
    "رئيس",
    "ملك",
    "أمير",
    "وزارة",
    "برلمان",
    "دستور",
    "علم",
    "نشيد",
    "وحدة وطنية",
    "شغب",
    "مظاهرة",
    "تظاهر",
    "ثورة",
    "انقلاب",
    "انتخابات",
    "تصويت",
  ]),
  directTerms: Object.freeze([
    "state_reference",
    "government_reference",
    "head_of_state",
    "royal_family",
    "government_institution",
    "public_official",
    "constitutional_reference",
    "state_scene_description",
    "state_observation",
    "national_flag",
    "national_anthem",
    "national_symbol",
    "national_identity",
    "national_unity",
    "patriotism",
    "foreign_government",
    "foreign_leader",
    "international_organization",
    "diplomatic_relations",
    "international_conflict",
    "state_security",
    "national_security",
    "treason",
    "espionage",
    "military_reference",
    "armed_forces",
    "intelligence_services",
    "police_institution",
    "political_dialogue",
    "political_debate",
    "political_satire",
    "political_criticism",
    "political_support",
    "political_glorification",
    "political_encouragement",
    "political_propaganda",
    "political_instruction",
    "political_documentary",
    "political_news",
    "political_historical",
    "political_educational",
    "political_rally",
    "public_demonstration",
    "civil_unrest",
    "riot",
    "revolution_reference",
    "coup_reference",
    "election_reference",
    "voting_reference",
    "دولة",
    "حكومة",
    "رئيس",
    "ملك",
    "أمير",
    "برلمان",
    "وزارة",
    "دستور",
    "علم الدولة",
    "نشيد وطني",
    "وحدة وطنية",
    "انقلاب",
    "ثورة",
    "شغب",
    "تظاهرة",
    "انتخابات",
    "تصويت",
  ]),
  stateTerms: Object.freeze([
    "state_reference",
    "government_reference",
    "government_institution",
    "public_official",
    "constitutional_reference",
    "state_scene_description",
    "state_observation",
    "diplomatic_relations",
    "international_conflict",
  ]),
  identityTerms: Object.freeze([
    "national_flag",
    "national_anthem",
    "national_symbol",
    "national_identity",
    "national_unity",
    "patriotism",
  ]),
  unrestTerms: Object.freeze([
    "public_demonstration",
    "civil_unrest",
    "riot",
    "revolution_reference",
    "coup_reference",
    "state_security",
    "national_security",
    "treason",
    "espionage",
    "إسقاط",
    "إسقاط الحكومة",
    "إسقاط النظام",
  ]),
  authorityTerms: Object.freeze([
    "public_official",
    "government_institution",
    "head_of_state",
    "royal_family",
    "abuse of authority",
    "humiliation",
    "coercion",
  ]),
  propagandaTerms: Object.freeze([
    "political_support",
    "political_glorification",
    "political_encouragement",
    "political_propaganda",
    "political_instruction",
    "incitement",
    "إسقاط",
    "تحريض",
    "دعاية",
    "تمجيد",
    "ترويج",
  ]),
  quotationSignals: Object.freeze(["quoted", "quote", "quotation", "«", "»", "\"", "اقتباس"]),
  educationalSignals: Object.freeze(["educational", "education", "instruction", "lesson", "شرح", "تعليمي", "درس"]),
  documentarySignals: Object.freeze(["documentary", "وثائقي", "تسجيلي", "archive"]),
  historicalSignals: Object.freeze(["historical", "history", "تاريخي", "تاريخ"]),
  newsSignals: Object.freeze(["news", "خبر", "reported", "report"]),
  courtSignals: Object.freeze(["court", "trial", "testimony", "محكمة", "شهادة"]),
  condemnationSignals: Object.freeze(["condemn", "condemnation", "أدين", "أرفض", "مرفوض", "wrong", "خطأ"]),
  fictionSignals: Object.freeze(["fiction", "story", "film", "movie", "novel", "رواية", "فيلم", "مسلسل"]),
  satireSignals: Object.freeze(["satire", "satirical", "ساخر", "سخرية", "تهكم"]),
  comedySignals: Object.freeze(["comedy", "comic", "كوميديا"]),
  dreamSignals: Object.freeze(["dream", "حلم", "منام"]),
  flashbackSignals: Object.freeze(["flashback", "استرجاع", "فلاش باك"]),
  rolePlaySignals: Object.freeze(["roleplay", "role play", "acting", "تمثيل", "مسرحية"]),
});
