export const FAMILY_VALUES_RULES = Object.freeze({
  familyAnchors: Object.freeze([
    "family",
    "family values",
    "family breakdown",
    "family destruction",
    "family respect",
    "family destruction",
    "parents",
    "parent",
    "mother",
    "father",
    "child",
    "children",
    "home",
    "household",
    "family cohesion",
    "العائلة",
    "الأسرة",
    "الأسري",
    "الأب",
    "الأم",
    "الطفل",
    "الأطفال",
    "البيت",
    "القيم الأسرية",
  ]),
  destructionTerms: Object.freeze([
    "family destruction",
    "destroy the family",
    "destroy family",
    "break the family",
    "family breakdown",
    "ruin the home",
    "tear the family apart",
    "تدمير الأسرة",
    "تفكيك الأسرة",
    "هدم البيت",
    "تخريب الأسرة",
  ]),
  abuseTerms: Object.freeze([
    "family abuse",
    "domestic abuse",
    "parental abuse",
    "abuse of the family",
    "abuse the family",
    "hit the mother",
    "hit the father",
    "hit the child",
    "mistreat",
    "mistreated",
    "إساءة أسرية",
    "إساءة للعائلة",
    "إهانة الأم",
    "إهانة الأب",
    "ضرب الأم",
    "ضرب الأب",
    "ضرب الطفل",
  ]),
  humiliationTerms: Object.freeze([
    "humiliation",
    "humiliate",
    "shame the family",
    "degrade the family",
    "belittle the parents",
    "mock the mother",
    "mock the father",
    "إذلال",
    "إهانة الأسرة",
    "تحقير الأسرة",
  ]),
  moralCorruptionTerms: Object.freeze([
    "moral corruption",
    "corrupt the family",
    "family corruption",
    "immorality",
    "depravity",
    "spread corruption",
    "glorify corruption",
    "فساد أخلاقي",
    "إفساد الأسرة",
    "ترويج الفساد",
  ]),
  neglectTerms: Object.freeze([
    "parental neglect",
    "neglect the child",
    "neglect the family",
    "abandon the child",
    "abandoned the child",
    "ignore the child",
    "family neglect",
    "إهمال أبوي",
    "إهمال الأسرة",
    "ترك الطفل",
    "هجر الطفل",
  ]),
  glorificationTerms: Object.freeze([
    "glorify",
    "glorification",
    "praise the destruction of the family",
    "celebrate the abuse",
    "encourage family destruction",
    "promote neglect",
    "تمجيد",
    "تمجيد تدمير الأسرة",
    "الاحتفال بالإساءة",
    "تشجيع الإهمال",
  ]),
  quotationSignals: Object.freeze([
    "quoted",
    "quote",
    "quotation",
    "said",
    "he said",
    "she said",
    "the text quotes",
  ]),
  educationalSignals: Object.freeze([
    "educational",
    "lesson",
    "explains",
    "explaining",
    "teacher",
    "classroom",
    "training",
    "instructional",
  ]),
  documentarySignals: Object.freeze([
    "documentary",
    "documented",
    "archival",
    "archive",
    "report",
    "reporting",
  ]),
  historicalSignals: Object.freeze([
    "historical",
    "history",
    "historically",
    "in the past",
    "years ago",
  ]),
  newsSignals: Object.freeze([
    "news",
    "report",
    "reported",
    "journalist",
    "breaking",
  ]),
  condemnationSignals: Object.freeze([
    "condemn",
    "condemns",
    "condemned",
    "denounce",
    "denounced",
    "rejects",
    "against this",
  ]),
  fictionSignals: Object.freeze([
    "fiction",
    "novel",
    "story",
    "movie",
    "scene",
    "script",
  ]),
  comedySignals: Object.freeze([
    "comedy",
    "comic",
    "joke",
    "humor",
  ]),
  satireSignals: Object.freeze([
    "satire",
    "satirical",
    "mocking satire",
  ]),
  dreamSignals: Object.freeze([
    "dream",
    "dreamed",
    "dream sequence",
  ]),
  flashbackSignals: Object.freeze([
    "flashback",
    "flashback scene",
    "earlier that day",
  ]),
  rolePlaySignals: Object.freeze([
    "role play",
    "roleplay",
    "acting",
    "performing",
  ]),
  supportSignals: Object.freeze([
    "family support",
    "family care",
    "care for the family",
    "respect the parents",
    "protect the children",
    "family cohesion",
    "family values",
    "دعم الأسرة",
    "رعاية الأسرة",
    "احترام الوالدين",
    "حماية الأطفال",
  ]),
} as const);
