ALTER TABLE public.analysis_findings
  ADD COLUMN IF NOT EXISTS lineage_id text NULL,
  ADD COLUMN IF NOT EXISTS parent_lineage_id text NULL,
  ADD COLUMN IF NOT EXISTS canonical_hash text NULL;

CREATE INDEX IF NOT EXISTS idx_analysis_findings_job_lineage
  ON public.analysis_findings (job_id, lineage_id);

CREATE INDEX IF NOT EXISTS idx_analysis_findings_job_canonical_hash
  ON public.analysis_findings (job_id, canonical_hash);

CREATE TABLE IF NOT EXISTS public.analysis_finding_lineage_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id uuid NOT NULL REFERENCES public.analysis_jobs(id) ON DELETE CASCADE,
  chunk_id uuid NULL REFERENCES public.analysis_chunks(id) ON DELETE SET NULL,
  lineage_id text NOT NULL,
  parent_lineage_id text NULL,
  stage_name text NOT NULL CHECK (stage_name IN ('pass_output', 'canonicalization', 'grounding', 'validation', 'aggregation', 'final_report')),
  pass_name text NULL,
  evidence_hash text NULL,
  canonical_hash text NULL,
  article_id int NULL,
  atom_id text NULL,
  start_offset int NULL,
  end_offset int NULL,
  reason_if_removed text NULL,
  metadata jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lineage_events_job_stage
  ON public.analysis_finding_lineage_events (job_id, stage_name, created_at);

CREATE INDEX IF NOT EXISTS idx_lineage_events_job_lineage
  ON public.analysis_finding_lineage_events (job_id, lineage_id, created_at);

CREATE INDEX IF NOT EXISTS idx_lineage_events_job_canonical
  ON public.analysis_finding_lineage_events (job_id, canonical_hash, created_at);
