ALTER TABLE public.analysis_judge_diagnostics
  ADD COLUMN IF NOT EXISTS rendered_system_prompt text NULL,
  ADD COLUMN IF NOT EXISTS rendered_user_prompt text NULL;

CREATE TABLE IF NOT EXISTS public.analysis_investigations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investigation_number text GENERATED ALWAYS AS ('INV-' || lpad(id::text, 6, '0')) STORED,
  created_at timestamptz NOT NULL DEFAULT now(),
  job_a uuid NOT NULL REFERENCES public.analysis_jobs(id) ON DELETE CASCADE,
  job_b uuid NOT NULL REFERENCES public.analysis_jobs(id) ON DELETE CASCADE,
  first_divergence_stage text NULL,
  first_divergence_pass text NULL,
  first_divergence_chunk integer NULL,
  root_cause_category text NOT NULL DEFAULT 'UNKNOWN'
    CHECK (root_cause_category IN ('PROMPT', 'MODEL', 'PARSER', 'PASS', 'VALIDATION', 'FINAL', 'UNKNOWN')),
  summary text NULL,
  CONSTRAINT analysis_investigations_job_pair_unique UNIQUE (job_a, job_b)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_analysis_investigations_number
  ON public.analysis_investigations (investigation_number);

CREATE INDEX IF NOT EXISTS idx_analysis_investigations_created_at
  ON public.analysis_investigations (created_at DESC);
