export const SOCIETY_RULES = Object.freeze({
  societyAnchors: Object.freeze([
    "society",
    "community",
    "civility",
    "social",
    "family",
    "parents",
    "mother",
    "father",
    "elderly",
    "disabled",
    "woman",
    "women",
    "children",
    "bullying",
    "harassment",
    "discrimination",
    "racism",
    "tribalism",
    "sectarianism",
    "hate speech",
    "hate",
    "stereotyping",
    "mockery",
    "insult",
    "humiliation",
    "defamation",
    "cultural insult",
    "tribal attack",
    "social exclusion",
    "public behavior",
    "public decency",
    "social media",
    "rumor spreading",
    "public panic",
    "community support",
    "social cohesion",
    "cultural identity",
    "national identity",
    "insulting the tribe",
    "التمييز",
    "عنصري",
    "عنصرية",
    "تمييز",
    "طائفي",
    "قبلية",
    "إهانة ثقافية",
    "إهانة المجتمع",
    "إهانة القبيلة",
    "إهانة العائلة",
    "سخرية",
    "تنمر",
  ]),
  directTerms: Object.freeze([
    "society_discrimination",
    "society_racism",
    "society_tribalism",
    "society_hate",
    "society_bullying",
    "society_harassment",
    "society_humiliation",
    "society_insult",
    "society_mockery",
    "society_defamation",
    "racism",
    "discrimination",
    "hate speech",
    "hate",
    "stereotyping",
    "sectarianism",
    "tribal attacks",
    "cultural insults",
    "bullying",
    "harassment",
    "mockery",
    "insult",
    "humiliation",
    "defamation",
    "social exclusion",
    "public panic",
    "rumor spreading",
    "cyber bullying",
    "cyberbullying",
    "family breakdown",
    "family disrespect",
    "racist",
    "prejudice",
    "bigotry",
    "عنصري",
    "عنصرية",
    "تمييز",
    "طائفي",
    "قبلية",
    "تحريض على الكراهية",
    "خطاب كراهية",
  ]),
  racismTerms: Object.freeze([
    "racism",
    "racist",
    "عنصري",
    "عنصرية",
    "العرق",
    "لون البشرة",
    "white superiority",
    "black inferiority",
  ]),
  discriminationTerms: Object.freeze([
    "discrimination",
    "prejudice",
    "تمييز",
    "يفرق",
    "يفرقون",
    "يعاملهم بشكل مختلف",
  ]),
  hateSpeechTerms: Object.freeze([
    "hate speech",
    "خطاب كراهية",
    "تحريض على الكراهية",
    "كره",
    "أكرهكم",
  ]),
  stereotypingTerms: Object.freeze([
    "stereotype",
    "stereotyping",
    "قالب نمطي",
    "كلهم",
    "دائمًا هكذا",
  ]),
  sectarianTerms: Object.freeze([
    "sectarianism",
    "sectarian",
    "طائفي",
    "طائفية",
    "مذهبي",
  ]),
  tribalTerms: Object.freeze([
    "tribal",
    "tribalism",
    "قبلية",
    "قبلي",
    "إهانة القبيلة",
  ]),
  culturalInsultTerms: Object.freeze([
    "cultural insult",
    "إهانة ثقافية",
    "إهانة المجتمع",
    "إهانة العادات",
    "إهانة التقاليد",
  ]),
  bullyingTerms: Object.freeze([
    "bullying",
    "تنمر",
    "تنمّر",
    "mockery",
    "humiliation",
    "harassment",
  ]),
  quotationSignals: Object.freeze([
    "\"",
    "«",
    "»",
    "quoted",
    "quote",
    "quotation",
    "اقتباس",
    "منقول",
  ]),
  condemnationSignals: Object.freeze([
    "condemn",
    "condemnation",
    "أدين",
    "أرفض",
    "مرفوض",
    "wrong",
    "خطأ",
    "سيء",
  ]),
  educationalSignals: Object.freeze([
    "educational",
    "education",
    "instruction",
    "teaching",
    "lesson",
    "شرح",
    "تعليمي",
    "درس",
    "توعية",
  ]),
  documentarySignals: Object.freeze([
    "documentary",
    "وثائقي",
    "تسجيلي",
    "reportage",
    "archive",
  ]),
  historicalSignals: Object.freeze([
    "historical",
    "history",
    "تاريخي",
    "تاريخ",
  ]),
  newsSignals: Object.freeze([
    "news",
    "خبر",
    "reported",
    "report",
  ]),
  fictionSignals: Object.freeze([
    "fiction",
    "story",
    "film",
    "movie",
    "novel",
    "رواية",
    "فيلم",
    "مسلسل",
  ]),
  satireSignals: Object.freeze([
    "satire",
    "satirical",
    "ساخر",
    "سخرية",
  ]),
  comedySignals: Object.freeze([
    "comedy",
    "comic",
    "كوميديا",
    "ساخر",
  ]),
  dreamSignals: Object.freeze([
    "dream",
    "حلم",
    "منام",
  ]),
  flashbackSignals: Object.freeze([
    "flashback",
    "استرجاع",
    "فلاش باك",
  ]),
  rolePlaySignals: Object.freeze([
    "roleplay",
    "role play",
    "acting",
    "تمثيل",
    "مسرحية",
  ]),
  supportSignals: Object.freeze([
    "support",
    "help",
    "community support",
    "charity",
    "kindness",
    "التعاون",
    "المساعدة",
  ]),
  familySignals: Object.freeze([
    "family",
    "parents",
    "mother",
    "father",
    "family values",
    "family respect",
    "العائلة",
    "الأب",
    "الأم",
  ]),
});
