export const STATE_LEADERSHIP_RULES = Object.freeze({
  stateAnchors: Object.freeze([
    "الدولة",
    "الحكومة",
    "الرئيس",
    "الملك",
    "الأمير",
    "الزعيم",
    "الحاكم",
    "القيادة",
    "السلطة",
    "الوزارة",
    "المسؤول",
    "المجلس",
    "البرلمان",
    "رأس الدولة",
    "رئيس الدولة",
  ]),
  respectTerms: Object.freeze([
    "احترام",
    "احترامًا",
    "تقدير",
    "وقار",
    "هيبة",
    "مهابة",
  ]),
  disrespectTerms: Object.freeze([
    "كذاب",
    "فاسد",
    "غبي",
    "أحمق",
    "خائن",
    "حقير",
    "تافه",
    "سخيف",
    "فاشل",
    "مخزي",
    "محتال",
  ]),
  incitementPhrases: Object.freeze([
    "اسقطوا",
    "اقلبوا الحكم",
    "اقلبوا الدولة",
    "اطردوا",
    "ارحل",
    "تمردوا",
    "ثوروا",
    "اهتفوا ضد",
    "أطيحوا",
    "أطيح",
    "احرقوا",
  ]),
  politicalContextSignals: Object.freeze([
    "سياسي",
    "سياسة",
    "سياسيا",
    "سياسية",
    "حكومة",
    "دولة",
    "رئاسة",
    "قيادة",
    "سلطة",
    "انتخابات",
    "خطاب",
    "معارضة",
  ]),
  quotationSignals: Object.freeze([
    "قال",
    "يقول",
    "اقتبس",
    "اقتباس",
    "quoted",
    "quote",
    "«",
    "»",
    "\"",
  ]),
  educationalSignals: Object.freeze([
    "تعليم",
    "تعليمي",
    "شرح",
    "نشرح",
    "درس",
    "الدرس",
    "example",
    "academic",
  ]),
  documentarySignals: Object.freeze([
    "وثائقي",
    "وثيقة",
    "documentary",
    "report",
    "تقرير",
    "archive",
    "أرشيف",
  ]),
  historicalSignals: Object.freeze([
    "تاريخ",
    "تاريخي",
    "historical",
    "سابقًا",
    "قديما",
    "سابق",
  ]),
  newsSignals: Object.freeze([
    "خبر",
    "إخباري",
    "news",
    "reported",
    "reporting",
    "وكالة",
  ]),
  courtSignals: Object.freeze([
    "محكمة",
    "قضاء",
    "القاضي",
    "testimony",
    "شهادة",
    "court",
  ]),
  condemnationSignals: Object.freeze([
    "أدين",
    "إدانة",
    "مرفوض",
    "نرفض",
    "condemn",
    "condemnation",
    "غير مقبول",
  ]),
  fictionSignals: Object.freeze([
    "رواية",
    "قصة",
    "خيال",
    "fiction",
    "مشهد تمثيلي",
  ]),
  rolePlaySignals: Object.freeze([
    "تمثيل",
    "دور",
    "roleplay",
    "role-play",
  ]),
  dreamSignals: Object.freeze([
    "حلم",
    "dream",
  ]),
  flashbackSignals: Object.freeze([
    "استرجاع",
    "flashback",
    "فلاش باك",
  ]),
  satireSignals: Object.freeze([
    "سخرية",
    "تهكم",
    "satire",
    "mockery",
  ]),
});

