export const NATIONAL_SECURITY_RULES = Object.freeze({
  securityAnchors: Object.freeze([
    "الأمن الوطني",
    "الأمن",
    "الأمن القومي",
    "الدولة",
    "الحكومة",
    "الجيش",
    "القوات المسلحة",
    "المخابرات",
    "الحدود",
    "الوطن",
    "سيادة",
    "الاستقرار",
    "national security",
    "security",
  ]),
  terrorismTerms: Object.freeze([
    "إرهاب",
    "إرهابي",
    "إرهابية",
    "متطرف",
    "متطرفة",
    "تطرف",
    "terrorism",
    "terrorist",
    "extremism",
    "extremist",
    "داعش",
    "القاعدة",
  ]),
  recruitmentTerms: Object.freeze([
    "جندوا",
    "جند",
    "يجند",
    "تجنيد",
    "انضموا",
    "انضم",
    "بايعوا",
    "بايع",
    "recruit",
    "recruitment",
    "join us",
  ]),
  incitementPhrases: Object.freeze([
    "اهجموا",
    "هاجموا",
    "فجروا",
    "دمروا",
    "احرقوا",
    "اسقطوا",
    "ثوروا",
    "تمردوا",
    "break into",
    "attack",
    "incite",
    "violent incitement",
  ]),
  sabotageTerms: Object.freeze([
    "تخريب",
    "sabotage",
    "تفجير",
    "تعطيل",
    "destroy",
    "disable",
    "cut communications",
    "قطع الاتصالات",
  ]),
  cyberTerms: Object.freeze([
    "هجوم إلكتروني",
    "اختراق",
    "قرصنة",
    "cyber",
    "cyber attack",
    "hacking",
    "hack",
    "ddos",
    "breach",
    "malware",
  ]),
  disclosureTerms: Object.freeze([
    "أسرار عسكرية",
    "معلومات سرية",
    "معلومات محظورة",
    "سربوا",
    "سرب",
    "كشفوا",
    "كشف",
    "leak",
    "disclosure",
    "classified",
    "secret",
    "military disclosure",
  ]),
  publicOrderTerms: Object.freeze([
    "شغب",
    "فوضى",
    "riot",
    "riots",
    "civil unrest",
    "public disorder",
    "mass panic",
    "اضطراب",
  ]),
  quotationSignals: Object.freeze([
    "قال",
    "يقول",
    "اقتبس",
    "اقتباس",
    "quoted",
    "quote",
    "«",
    "»",
    "\"",
  ]),
  educationalSignals: Object.freeze([
    "تعليم",
    "تعليمي",
    "شرح",
    "نشرح",
    "درس",
    "الدرس",
    "example",
    "academic",
  ]),
  documentarySignals: Object.freeze([
    "وثائقي",
    "وثيقة",
    "documentary",
    "report",
    "تقرير",
    "archive",
    "أرشيف",
  ]),
  historicalSignals: Object.freeze([
    "تاريخ",
    "تاريخي",
    "historical",
    "سابقًا",
    "قديما",
    "سابق",
  ]),
  newsSignals: Object.freeze([
    "خبر",
    "إخباري",
    "news",
    "reported",
    "reporting",
    "وكالة",
  ]),
  courtSignals: Object.freeze([
    "محكمة",
    "قضاء",
    "القاضي",
    "testimony",
    "شهادة",
    "court",
  ]),
  condemnationSignals: Object.freeze([
    "أدين",
    "إدانة",
    "مرفوض",
    "نرفض",
    "condemn",
    "condemnation",
    "غير مقبول",
  ]),
  fictionSignals: Object.freeze([
    "رواية",
    "قصة",
    "خيال",
    "fiction",
    "مشهد تمثيلي",
  ]),
  rolePlaySignals: Object.freeze([
    "تمثيل",
    "دور",
    "roleplay",
    "role-play",
  ]),
  dreamSignals: Object.freeze([
    "حلم",
    "dream",
  ]),
  flashbackSignals: Object.freeze([
    "استرجاع",
    "flashback",
    "فلاش باك",
  ]),
  satireSignals: Object.freeze([
    "سخرية",
    "تهكم",
    "satire",
    "mockery",
  ]),
});

