import React from "react";
import { Page, Text, View, Document, Image } from "@react-pdf/renderer";
import { formatDate, formatDateLong } from "@/utils/dateFormat";
import { styles } from "./ReportStyles";

interface ReportLayoutProps {
  children: React.ReactNode;
  title: string;
  lang?: "ar" | "en";
  clientName?: string;
  dateFormat?: string;
  logoUrl?: string;
  footerNoteAr?: string;
  footerNoteEn?: string;
}

export const ReportLayout: React.FC<ReportLayoutProps> = ({
  children,
  title,
  lang = "en",
  clientName,
  dateFormat,
  logoUrl,
  footerNoteAr,
  footerNoteEn,
}) => {
  const isAr = lang === "ar";
  const dateStr = dateFormat
    ? formatDate(new Date(), { lang, format: dateFormat })
    : formatDateLong(new Date(), { lang });
  const headerLogo = logoUrl || "/dashboardlogo.png";
  const footerText = isAr ? (footerNoteAr || "Generated by Rawwi Platform") : (footerNoteEn || "Generated by Rawwi Platform");

  return (
    <Document>
      <Page size="A4" style={[styles.page, isAr ? styles.pageAr : {}]}>
        {/* Header */}
        <View style={[styles.headerContainer, isAr ? styles.rowReverse : {}]}>
          <View style={{ width: 100 }}>
            {/* eslint-disable-next-line jsx-a11y/alt-text */}
            <Image src={headerLogo} style={{ height: 30, objectFit: "contain" }} />
          </View>
          <View style={{ alignItems: isAr ? "flex-start" : "flex-end" }}>
            <Text style={[styles.headerText, isAr ? styles.rtlText : {}]}>
              {isAr ? "تقرير آلي" : "Generated Report"}
            </Text>
            <Text style={[styles.headerText, isAr ? styles.rtlText : {}]}>
              {dateStr}
            </Text>
          </View>
        </View>

        {/* Title */}
        <View style={{ marginBottom: 20 }}>
          <Text
            style={[
              { fontSize: 24, fontWeight: "bold", textAlign: "center", marginBottom: 5 },
              isAr ? styles.pageAr : {},
            ]}
          >
            {title}
          </Text>
          {clientName && (
            <Text
              style={[
                { fontSize: 12, textAlign: "center", color: "#6B7280" },
                isAr ? styles.pageAr : {},
              ]}
            >
              {isAr ? `العميل: ${clientName}` : `Client: ${clientName}`}
            </Text>
          )}
        </View>

        {children}

        {/* Footer */}
        <View style={[styles.footerContainer, isAr ? styles.rowReverse : {}]}>
          <Text style={styles.footerText}>{footerText}</Text>
          <Text
            style={styles.footerText}
            render={({ pageNumber, totalPages }) =>
              `${pageNumber} / ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
};
